"""Extended cross-verification tests.

Cross-verifies PKCS#11 operations against the Python cryptography library
for operations not covered in test_crossverify.py: AES-CBC, AES-GCM,
RSA-OAEP encrypt/decrypt, and RSA-PSS sign/verify.
"""

from __future__ import annotations

from typing import Any

import pytest
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding as rsa_padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from pkcs11_check.raw.pack import mech_bytes, mech_gcm, mech_oaep, mech_pss
from pkcs11_check.raw.recipes import (
    decrypt_single,
    destroy_quietly,
    encrypt_single,
    gen_rsa_keypair,
    import_secret_key,
    sign_single,
)
from pkcs11_check.raw.types_std import (
    CKA_ALLOWED_MECHANISMS,
    CKA_DECRYPT,
    CKA_ENCRYPT,
    CKA_EXTRACTABLE,
    CKA_SENSITIVE,
    CKA_TOKEN,
    CKG_MGF1_SHA1,
    CKG_MGF1_SHA256,
    CKK_AES,
    CKM_AES_CBC,
    CKM_AES_GCM,
    CKM_RSA_PKCS_OAEP,
    CKM_SHA256,
    CKM_SHA256_RSA_PKCS_PSS,
    CKM_SHA_1,
)
from pkcs11_check.testcases._interop_runtime import xfail_if_interop_operation_reject
from pkcs11_check.testcases._rsa_export import (
    read_rsa_private_key_or_xfail,
    read_rsa_public_key_or_xfail,
)

pytestmark = pytest.mark.crossverify


def _import_aes_key_raw(rs: Any, key_bytes: bytes, *allowed_mechanisms: int) -> int:
    """Import raw AES key bytes via raw API."""
    attrs: dict[Any, Any] = {
        CKA_ENCRYPT: True,
        CKA_DECRYPT: True,
        CKA_TOKEN: False,
        CKA_SENSITIVE: False,
        CKA_EXTRACTABLE: True,
    }
    if allowed_mechanisms:
        attrs[CKA_ALLOWED_MECHANISMS] = [int(mech) for mech in allowed_mechanisms]
    return import_secret_key(
        rs.raw,
        rs.sh,
        CKK_AES,
        key_bytes,
        attrs=attrs,
    )


class TestAESCBCCrossVerify:
    """Cross-verify AES-CBC against cryptography library."""

    def test_aes_cbc_encrypt_crossverify(self, p11_raw_session: Any) -> None:
        """AES-CBC encryption matches cryptography library output."""
        rs = p11_raw_session
        key_bytes = bytes(range(32))
        iv = bytes(range(16))
        data = b"\xaa" * 64  # 4 blocks

        # PKCS#11
        p11_key = _import_aes_key_raw(rs, key_bytes, CKM_AES_CBC)
        try:
            try:
                ct_p11 = encrypt_single(
                    rs.raw,
                    rs.sh,
                    p11_key,
                    CKM_AES_CBC,
                    data,
                    mech_param=mech_bytes(CKM_AES_CBC, iv),
                )
            except AssertionError as exc:
                xfail_if_interop_operation_reject(exc, "AES_CBC encrypt")

            # cryptography
            cipher = Cipher(algorithms.AES(key_bytes), modes.CBC(iv))
            enc = cipher.encryptor()
            ct_crypto = enc.update(data) + enc.finalize()

            assert ct_p11 == ct_crypto
        finally:
            destroy_quietly(rs.raw, rs.sh, p11_key)

    def test_aes_cbc_decrypt_crossverify(self, p11_raw_session: Any) -> None:
        """AES-CBC decryption of cryptography-generated ciphertext works."""
        rs = p11_raw_session
        key_bytes = bytes(range(32))
        iv = b"\x00" * 16
        data = b"\xbb" * 48

        # Encrypt with cryptography
        cipher = Cipher(algorithms.AES(key_bytes), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(data) + enc.finalize()

        # Decrypt with PKCS#11
        p11_key = _import_aes_key_raw(rs, key_bytes, CKM_AES_CBC)
        try:
            try:
                pt = decrypt_single(
                    rs.raw,
                    rs.sh,
                    p11_key,
                    CKM_AES_CBC,
                    ct,
                    mech_param=mech_bytes(CKM_AES_CBC, iv),
                )
            except AssertionError as exc:
                xfail_if_interop_operation_reject(exc, "AES_CBC decrypt")
            assert pt == data
        finally:
            destroy_quietly(rs.raw, rs.sh, p11_key)


class TestAESGCMCrossVerify:
    """Cross-verify AES-GCM against cryptography library."""

    def test_aes_gcm_decrypt_crossverify(self, p11_raw_session: Any) -> None:
        """Decrypt ciphertext generated by cryptography library."""
        rs = p11_raw_session
        if not rs.has_mechanism("AES_GCM"):
            pytest.skip("CKM_AES_GCM not supported")

        key_bytes = bytes(range(32))
        plaintext = b"AES-GCM cross-verify test data!!"
        iv = bytes(range(12))  # 96-bit nonce

        # Encrypt with cryptography
        aesgcm = AESGCM(key_bytes)
        ct_tag = aesgcm.encrypt(iv, plaintext, None)
        # ct_tag = ciphertext || tag (16 bytes)

        # Decrypt with PKCS#11
        p11_key = _import_aes_key_raw(rs, key_bytes, CKM_AES_GCM)
        try:
            gcm = mech_gcm(CKM_AES_GCM, iv, tag_bits=128)
            pt = decrypt_single(
                rs.raw,
                rs.sh,
                p11_key,
                CKM_AES_GCM,
                ct_tag,
                mech_param=gcm,
            )
            assert pt == plaintext
        except AssertionError:
            # Some modules need different GCM parameter format
            pytest.skip("AES-GCM parameter format incompatible")
        finally:
            destroy_quietly(rs.raw, rs.sh, p11_key)


class TestRSAPSSCrossVerify:
    """Cross-verify RSA-PSS against cryptography library."""

    def test_rsa_pss_sign_p11_verify_crypto(self, p11_raw_session: Any) -> None:
        """Sign with PKCS#11 RSA-PSS, verify with cryptography."""
        rs = p11_raw_session
        if not rs.has_mechanism("SHA256_RSA_PKCS_PSS"):
            pytest.skip("RSA-PSS not supported")

        pub, priv = gen_rsa_keypair(rs.raw, rs.sh, 2048)
        try:
            data = b"RSA-PSS cross-verify test"
            pss = mech_pss(
                CKM_SHA256_RSA_PKCS_PSS,
                hash_mech=CKM_SHA256,
                mgf=CKG_MGF1_SHA256,
                salt_len=32,
            )
            sig = sign_single(
                rs.raw,
                rs.sh,
                priv,
                CKM_SHA256_RSA_PKCS_PSS,
                data,
                mech_param=pss,
            )

            # Export public key components
            # Reconstruct public key in cryptography
            crypto_pub = read_rsa_public_key_or_xfail(rs, pub)

            # Verify with cryptography (PSS with SHA-256)
            try:
                crypto_pub.verify(
                    sig,
                    data,
                    rsa_padding.PSS(
                        mgf=rsa_padding.MGF1(hashes.SHA256()),
                        salt_length=rsa_padding.PSS.AUTO,
                    ),
                    hashes.SHA256(),
                )
            except Exception:
                pytest.fail("cryptography failed to verify PKCS#11 RSA-PSS signature")
        finally:
            destroy_quietly(rs.raw, rs.sh, pub)
            destroy_quietly(rs.raw, rs.sh, priv)


class TestRSAOAEPCrossVerify:
    """Cross-verify RSA-OAEP against cryptography library."""

    def test_rsa_oaep_encrypt_p11_decrypt_crypto(self, p11_raw_session: Any) -> None:
        """Encrypt with PKCS#11 RSA-OAEP, decrypt with cryptography."""
        rs = p11_raw_session
        if not rs.has_mechanism("RSA_PKCS_OAEP"):
            pytest.skip("RSA-OAEP not supported")

        pub, priv = gen_rsa_keypair(
            rs.raw,
            rs.sh,
            2048,
            private_attrs={
                CKA_SENSITIVE: False,
                CKA_EXTRACTABLE: True,
            },
        )
        try:
            plaintext = b"OAEP cross-verify"
            oaep = mech_oaep(
                CKM_RSA_PKCS_OAEP,
                hash_mech=CKM_SHA_1,
                mgf=CKG_MGF1_SHA1,
            )
            ct = encrypt_single(
                rs.raw,
                rs.sh,
                pub,
                CKM_RSA_PKCS_OAEP,
                plaintext,
                mech_param=oaep,
            )

            # Export private key components for cryptography
            crypto_priv = read_rsa_private_key_or_xfail(rs, priv)

            # Decrypt with cryptography (OAEP SHA-1, default for PKCS#11)
            pt = crypto_priv.decrypt(
                ct,
                rsa_padding.OAEP(
                    # Intentional PKCS#11 OAEP SHA-1 default compatibility coverage.
                    mgf=rsa_padding.MGF1(algorithm=hashes.SHA1()),  # nosec B303
                    algorithm=hashes.SHA1(),  # nosec B303
                    label=None,
                ),
            )
            assert pt == plaintext
        finally:
            destroy_quietly(rs.raw, rs.sh, pub)
            destroy_quietly(rs.raw, rs.sh, priv)
