"""Mechanism-driven key generation tests.

Parametrized by mech_keygen_entry -- tests every keygen mechanism
advertised by the module that also has a registry config.

Key types covered:
- Symmetric variable-length (AES, Camellia, ChaCha20, ARIA, generic):
  uses CKA_VALUE_LEN
- Symmetric fixed-length (DES, DES3, SEED): no CKA_VALUE_LEN, module determines size
- RSA keypairs: CKA_MODULUS_BITS in public template
- EC (Weierstrass / Edwards / Montgomery) keypairs: CKA_EC_PARAMS (P-256 default)
- PQC keypairs (ML-KEM, ML-DSA, SLH-DSA): CKA_PARAMETER_SET
- DSA / DH / X9.42 DH / KEA / GOSTR: need domain parameters -- skipped
"""

from __future__ import annotations

import pytest

from pkcs11_check.fixtures import RawSession
from pkcs11_check.raw.recipes import destroy_quietly, read_attributes
from pkcs11_check.raw.types_std import (
    CKA_LOCAL,
)
from pkcs11_check.testcases.mechanism_catalog import MechEntry
from pkcs11_check.testcases.mechanism_helpers import (
    gen_keypair_for_mech,
    gen_symmetric_key,
)

pytestmark = [pytest.mark.mechanism_coverage, pytest.mark.keygen]


class TestMechKeygen:
    """Key generation for every advertised keygen mechanism with a registry config."""

    def test_generate_key(self, p11_raw_session: RawSession, mech_keygen_entry: MechEntry) -> None:
        """Generate a key/keypair and verify the returned handle is non-zero."""
        rs = p11_raw_session
        entry = mech_keygen_entry
        config = entry.config
        if config is None:
            pytest.skip("No registry config")
        if config.is_param_gen:
            pytest.skip("Domain parameter generation not covered by this test")

        if config.is_keypair:
            pub, priv = gen_keypair_for_mech(rs, entry, config)
            try:
                assert pub != 0, f"{entry.mech_name}: public key handle is 0"
                assert priv != 0, f"{entry.mech_name}: private key handle is 0"
            finally:
                destroy_quietly(rs.raw, rs.sh, pub)
                destroy_quietly(rs.raw, rs.sh, priv)
        else:
            key = gen_symmetric_key(rs, entry, config)
            try:
                assert key != 0, f"{entry.mech_name}: secret key handle is 0"
            finally:
                destroy_quietly(rs.raw, rs.sh, key)

    def test_local_flag(self, p11_raw_session: RawSession, mech_keygen_entry: MechEntry) -> None:
        """Keys generated by C_GenerateKey/C_GenerateKeyPair must have CKA_LOCAL=True."""
        rs = p11_raw_session
        entry = mech_keygen_entry
        config = entry.config
        if config is None:
            pytest.skip("No registry config")
        if config.is_param_gen:
            pytest.skip("Domain parameter generation not covered by this test")

        if config.is_keypair:
            pub, priv = gen_keypair_for_mech(rs, entry, config)
            try:
                for label, handle in (("public", pub), ("private", priv)):
                    attrs = read_attributes(rs.raw, rs.sh, handle, [CKA_LOCAL])
                    if CKA_LOCAL in attrs:
                        assert attrs[CKA_LOCAL] is True, (
                            f"{entry.mech_name}: CKA_LOCAL should be True on generated "
                            f"{label} key (got {attrs[CKA_LOCAL]!r})"
                        )
            finally:
                destroy_quietly(rs.raw, rs.sh, pub)
                destroy_quietly(rs.raw, rs.sh, priv)
        else:
            key = gen_symmetric_key(rs, entry, config)
            try:
                attrs = read_attributes(rs.raw, rs.sh, key, [CKA_LOCAL])
                if CKA_LOCAL in attrs:
                    assert attrs[CKA_LOCAL] is True, (
                        f"{entry.mech_name}: CKA_LOCAL should be True on generated key "
                        f"(got {attrs[CKA_LOCAL]!r})"
                    )
            finally:
                destroy_quietly(rs.raw, rs.sh, key)
