"""Mechanism-driven key generation tests.

Parametrized by mech_keygen_entry -- tests every keygen mechanism
advertised by the module that also has a registry config.

Key types covered:
- Symmetric variable-length (AES, Camellia, ChaCha20, ARIA, generic):
  uses CKA_VALUE_LEN
- Symmetric fixed-length (DES, DES3, SEED): no CKA_VALUE_LEN, module determines size
- RSA keypairs: CKA_MODULUS_BITS in public template
- EC (Weierstrass / Edwards / Montgomery) keypairs: CKA_EC_PARAMS (P-256 default)
- PQC keypairs (ML-KEM, ML-DSA, SLH-DSA): CKA_PARAMETER_SET
- DSA / DH / X9.42 DH / KEA / GOSTR: need domain parameters -- skipped
"""

from __future__ import annotations

from typing import Any

import pytest

from pkcs11_check.classification import classify, xfail_as
from pkcs11_check.fixtures import RawSession
from pkcs11_check.raw.recipes import destroy_quietly, read_attributes
from pkcs11_check.raw.rv import ckr_name
from pkcs11_check.raw.types_std import (
    CKA_LOCAL,
    CKR_ATTRIBUTE_SENSITIVE,
    CKR_ATTRIBUTE_TYPE_INVALID,
    CKR_ATTRIBUTE_VALUE_INVALID,
    CKR_TEMPLATE_INCONSISTENT,
)
from pkcs11_check.testcases.conftest import is_known_error
from pkcs11_check.testcases.mechanism_catalog import MechEntry
from pkcs11_check.testcases.mechanism_helpers import (
    gen_keypair_for_mech,
    gen_symmetric_key,
)

pytestmark = [pytest.mark.mechanism_coverage, pytest.mark.keygen]

_LOCAL_READ_UNSUPPORTED_RVS = (
    CKR_ATTRIBUTE_TYPE_INVALID,
    CKR_ATTRIBUTE_SENSITIVE,
    CKR_TEMPLATE_INCONSISTENT,
)

_LOCAL_READ_NONCLEAN_RVS = (CKR_ATTRIBUTE_VALUE_INVALID,)


def _read_local_flag(rs: RawSession, handle: int, label: str) -> Any | None:
    """Read CKA_LOCAL; return None when the provider does not expose it."""
    try:
        attrs = read_attributes(rs.raw, rs.sh, handle, [CKA_LOCAL])
    except AssertionError as exc:
        if is_known_error(exc, _LOCAL_READ_UNSUPPORTED_RVS):
            return None
        if is_known_error(exc, _LOCAL_READ_NONCLEAN_RVS):
            rv = int(getattr(exc, "rv", CKR_ATTRIBUTE_VALUE_INVALID))
            xfail_as(
                "not_operational",
                kind="metadata",
                label=f"{label}:CKA_LOCAL",
                operation="C_GetAttributeValue",
                actual=rv,
                summary=f"{label} CKA_LOCAL read rejected with non-clean CKR: {ckr_name(rv)}",
            )
        raise AssertionError(
            f"Unexpected error reading CKA_LOCAL on handle {handle}: {exc}"
        ) from exc
    return attrs.get(CKA_LOCAL)


def _xfail_generated_local_false(mech_name: str, label: str) -> None:
    from pkcs11_check.compliance import ComplianceLevel, note

    note(
        f"{mech_name} {label} CKA_LOCAL=False for generated key",
        ComplianceLevel.NOT_RECOMMENDED,
        reference="PKCS#11 v3.1 Sec.4.9.2: CKA_LOCAL True if key generated on token",
    )
    classify(
        "honest_deviation",
        kind="metadata",
        label=f"{mech_name}:{label}:CKA_LOCAL",
        mechanism=mech_name,
        summary=f"{mech_name} {label}: CKA_LOCAL=False for generated key",
    )


class TestMechKeygen:
    """Key generation for every advertised keygen mechanism with a registry config."""

    def test_generate_key(
        self, p11_module_session: RawSession, mech_keygen_entry: MechEntry
    ) -> None:
        """Generate a key/keypair and verify the returned handle is non-zero."""
        rs = p11_module_session
        entry = mech_keygen_entry
        config = entry.config
        if config is None:
            pytest.skip("No registry config")
        if config.is_param_gen:
            pytest.skip("Domain parameter generation not covered by this test")

        if config.is_keypair:
            pub, priv = gen_keypair_for_mech(rs, entry, config)
            try:
                assert pub != 0, f"{entry.mech_name}: public key handle is 0"
                assert priv != 0, f"{entry.mech_name}: private key handle is 0"
            finally:
                destroy_quietly(rs.raw, rs.sh, pub)
                destroy_quietly(rs.raw, rs.sh, priv)
        else:
            key = gen_symmetric_key(rs, entry, config)
            try:
                assert key != 0, f"{entry.mech_name}: secret key handle is 0"
            finally:
                destroy_quietly(rs.raw, rs.sh, key)

    def test_local_flag(self, p11_module_session: RawSession, mech_keygen_entry: MechEntry) -> None:
        """Keys generated by C_GenerateKey/C_GenerateKeyPair must have CKA_LOCAL=True."""
        rs = p11_module_session
        entry = mech_keygen_entry
        config = entry.config
        if config is None:
            pytest.skip("No registry config")
        if config.is_param_gen:
            pytest.skip("Domain parameter generation not covered by this test")

        if config.is_keypair:
            pub, priv = gen_keypair_for_mech(rs, entry, config)
            try:
                for label, handle in (("public", pub), ("private", priv)):
                    local = _read_local_flag(rs, handle, f"{entry.mech_name} {label} key")
                    if local is not None:
                        if local is False:
                            _xfail_generated_local_false(entry.mech_name, f"{label} key")
                        assert local is True, (
                            f"{entry.mech_name}: CKA_LOCAL should be True on generated "
                            f"{label} key (got {local!r})"
                        )
            finally:
                destroy_quietly(rs.raw, rs.sh, pub)
                destroy_quietly(rs.raw, rs.sh, priv)
        else:
            key = gen_symmetric_key(rs, entry, config)
            try:
                local = _read_local_flag(rs, key, f"{entry.mech_name} key")
                if local is not None:
                    if local is False:
                        _xfail_generated_local_false(entry.mech_name, "key")
                    assert local is True, (
                        f"{entry.mech_name}: CKA_LOCAL should be True on generated key "
                        f"(got {local!r})"
                    )
            finally:
                destroy_quietly(rs.raw, rs.sh, key)
