#!/usr/bin/env python3
"""Generate PKCS#11 mechanism KAT vectors using the cryptography library.

Usage:
    uv run python scripts/generate_mechanism_vectors.py --all
    uv run python scripts/generate_mechanism_vectors.py --family aes_ecb
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

OUTPUT_DIR = Path("src/pkcs11_check/testcases/data/mechanism_vectors")


def _fixed_bytes(n: int, seed: int = 42) -> bytes:
    """Deterministic bytes for reproducible vectors."""
    import hashlib

    result = b""
    counter = seed
    while len(result) < n:
        result += hashlib.sha256(counter.to_bytes(8, "big")).digest()
        counter += 1
    return result[:n]


def generate_aes_ecb() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=100 + bits)
        plaintext = _fixed_bytes(32, seed=200 + bits)  # 2 blocks
        cipher = Cipher(algorithms.AES(key), modes.ECB())
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_ecb_{bits}_2blocks",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_ECB",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_cbc() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=300 + bits)
        iv = _fixed_bytes(16, seed=400 + bits)
        plaintext = _fixed_bytes(32, seed=500 + bits)
        cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_cbc_{bits}_2blocks",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CBC",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_gcm() -> dict:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=600 + bits)
        iv = _fixed_bytes(12, seed=700 + bits)
        plaintext = _fixed_bytes(32, seed=800 + bits)
        aad = _fixed_bytes(16, seed=900 + bits)
        aesgcm = AESGCM(key)
        ct_tag = aesgcm.encrypt(iv, plaintext, aad)
        ct = ct_tag[:-16]
        tag = ct_tag[-16:]
        vectors.append(
            {
                "id": f"aes_gcm_{bits}_with_aad",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex(), "aad_hex": aad.hex(), "tag_bits": 128},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
                "tag_hex": tag.hex(),
            }
        )
        # Also without AAD
        ct_tag2 = aesgcm.encrypt(iv, plaintext, None)
        vectors.append(
            {
                "id": f"aes_gcm_{bits}_no_aad",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex(), "aad_hex": "", "tag_bits": 128},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct_tag2[:-16].hex(),
                "tag_hex": ct_tag2[-16:].hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_GCM",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_sha() -> dict:
    import hashlib

    vectors = []
    test_inputs = [
        ("empty", b""),
        ("abc", b"abc"),
        ("long", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
    ]
    for algo, name, digest_len in [
        ("sha1", "SHA_1", 20),
        ("sha224", "SHA224", 28),
        ("sha256", "SHA256", 32),
        ("sha384", "SHA384", 48),
        ("sha512", "SHA512", 64),
    ]:
        for input_id, input_data in test_inputs:
            h = hashlib.new(algo)
            h.update(input_data)
            vectors.append(
                {
                    "id": f"{name}_{input_id}",
                    "type": "positive",
                    "mechanism_name": f"CKM_{name}",
                    "input_hex": input_data.hex(),
                    "digest_hex": h.hexdigest(),
                    "digest_len": digest_len,
                }
            )
    return {
        "mechanism": "CKM_SHA_*",
        "family": "sha",
        "key_type": None,
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac() -> dict:
    import hmac

    vectors = []
    for algo, name, key_len in [
        ("sha256", "SHA256_HMAC", 32),
        ("sha384", "SHA384_HMAC", 48),
        ("sha512", "SHA512_HMAC", 64),
    ]:
        key = _fixed_bytes(key_len, seed=1000 + key_len)
        data = _fixed_bytes(64, seed=1100 + key_len)
        mac = hmac.new(key, data, algo).digest()
        vectors.append(
            {
                "id": f"{name}_basic",
                "type": "positive",
                "mechanism_name": f"CKM_{name}",
                "key_hex": key.hex(),
                "key_bits": key_len * 8,
                "input_hex": data.hex(),
                "mac_hex": mac.hex(),
            }
        )
    return {
        "mechanism": "CKM_SHA*_HMAC",
        "family": "hmac",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_cbc_pad() -> dict:
    from cryptography.hazmat.primitives import padding
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=1200 + bits)
        iv = _fixed_bytes(16, seed=1300 + bits)
        plaintext = _fixed_bytes(31, seed=1400 + bits)  # non-block-aligned to test padding
        padder = padding.PKCS7(128).padder()
        padded = padder.update(plaintext) + padder.finalize()
        cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(padded) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_cbc_pad_{bits}_31bytes",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CBC_PAD",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_ctr() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=1500 + bits)
        nonce = _fixed_bytes(16, seed=1600 + bits)  # full 16-byte counter block
        plaintext = _fixed_bytes(32, seed=1700 + bits)
        cipher = Cipher(algorithms.AES(key), modes.CTR(nonce))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_ctr_{bits}_32bytes",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": nonce.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CTR",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_des3_ecb() -> dict:
    from cryptography.hazmat.decrepit.ciphers.algorithms import TripleDES
    from cryptography.hazmat.primitives.ciphers import Cipher, modes

    key = _fixed_bytes(24, seed=1800)  # 24-byte (3-key) Triple-DES key
    plaintext = _fixed_bytes(16, seed=1900)  # 2 DES blocks (8 bytes each)
    cipher = Cipher(TripleDES(key), modes.ECB())
    enc = cipher.encryptor()
    ct = enc.update(plaintext) + enc.finalize()
    vectors = [
        {
            "id": "des3_ecb_192_2blocks",
            "type": "positive",
            "key_bits": 192,
            "key_hex": key.hex(),
            "params": {},
            "plaintext_hex": plaintext.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_DES3_ECB",
        "family": "des3",
        "key_type": "CKK_DES3",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_des3_cbc() -> dict:
    from cryptography.hazmat.decrepit.ciphers.algorithms import TripleDES
    from cryptography.hazmat.primitives.ciphers import Cipher, modes

    key = _fixed_bytes(24, seed=2000)  # 24-byte (3-key) Triple-DES key
    iv = _fixed_bytes(8, seed=2100)  # 8-byte DES IV
    plaintext = _fixed_bytes(16, seed=2200)  # 2 DES blocks
    cipher = Cipher(TripleDES(key), modes.CBC(iv))
    enc = cipher.encryptor()
    ct = enc.update(plaintext) + enc.finalize()
    vectors = [
        {
            "id": "des3_cbc_192_2blocks",
            "type": "positive",
            "key_bits": 192,
            "key_hex": key.hex(),
            "params": {"iv_hex": iv.hex()},
            "plaintext_hex": plaintext.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_DES3_CBC",
        "family": "des3",
        "key_type": "CKK_DES3",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_sha256() -> dict:
    import hmac

    key_len = 32
    key = _fixed_bytes(key_len, seed=1000 + key_len)
    data = _fixed_bytes(64, seed=1100 + key_len)
    mac = hmac.new(key, data, "sha256").digest()
    vectors = [
        {
            "id": "SHA256_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_SHA256_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SHA256_HMAC",
        "family": "hmac",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_sha384() -> dict:
    import hmac

    key_len = 48
    key = _fixed_bytes(key_len, seed=1000 + key_len)
    data = _fixed_bytes(64, seed=1100 + key_len)
    mac = hmac.new(key, data, "sha384").digest()
    vectors = [
        {
            "id": "SHA384_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_SHA384_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SHA384_HMAC",
        "family": "hmac",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_sha512() -> dict:
    import hmac

    key_len = 64
    key = _fixed_bytes(key_len, seed=1000 + key_len)
    data = _fixed_bytes(64, seed=1100 + key_len)
    mac = hmac.new(key, data, "sha512").digest()
    vectors = [
        {
            "id": "SHA512_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_SHA512_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SHA512_HMAC",
        "family": "hmac",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_sha3() -> dict:
    import hashlib

    vectors = []
    test_inputs = [
        ("empty", b""),
        ("abc", b"abc"),
        ("long", b"a" * 1000),
    ]
    for algo, name, digest_len in [
        ("sha3_224", "SHA3_224", 28),
        ("sha3_256", "SHA3_256", 32),
        ("sha3_384", "SHA3_384", 48),
        ("sha3_512", "SHA3_512", 64),
    ]:
        for input_id, input_data in test_inputs:
            h = hashlib.new(algo)
            h.update(input_data)
            vectors.append(
                {
                    "id": f"{name}_{input_id}",
                    "type": "positive",
                    "mechanism_name": f"CKM_{name}",
                    "input_hex": input_data.hex(),
                    "digest_hex": h.hexdigest(),
                    "digest_len": digest_len,
                }
            )
    return {
        "mechanism": "CKM_SHA3_*",
        "family": "sha3",
        "key_type": None,
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_sha512_truncated() -> dict:
    import hashlib

    vectors = []
    test_inputs = [
        ("empty", b""),
        ("abc", b"abc"),
        ("long", b"a" * 1000),
    ]
    for algo, name, digest_len in [
        ("sha512_224", "SHA512_224", 28),
        ("sha512_256", "SHA512_256", 32),
    ]:
        if algo not in hashlib.algorithms_available:
            continue
        for input_id, input_data in test_inputs:
            h = hashlib.new(algo)
            h.update(input_data)
            vectors.append(
                {
                    "id": f"{name}_{input_id}",
                    "type": "positive",
                    "mechanism_name": f"CKM_{name}",
                    "input_hex": input_data.hex(),
                    "digest_hex": h.hexdigest(),
                    "digest_len": digest_len,
                }
            )
    return {
        "mechanism": "CKM_SHA512_224 / CKM_SHA512_256",
        "family": "sha512_truncated",
        "key_type": None,
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_sha1() -> dict:
    import hmac

    key_len = 20
    key = _fixed_bytes(key_len, seed=3000 + key_len)
    data = _fixed_bytes(64, seed=3100 + key_len)
    mac = hmac.new(key, data, "sha1").digest()
    vectors = [
        {
            "id": "SHA_1_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_SHA_1_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SHA_1_HMAC",
        "family": "hmac_sha1",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_sha224() -> dict:
    import hmac

    key_len = 28
    key = _fixed_bytes(key_len, seed=3000 + key_len)
    data = _fixed_bytes(64, seed=3100 + key_len)
    mac = hmac.new(key, data, "sha224").digest()
    vectors = [
        {
            "id": "SHA224_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_SHA224_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SHA224_HMAC",
        "family": "hmac_sha224",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac_md5() -> dict:
    import hmac

    key_len = 16
    key = _fixed_bytes(key_len, seed=3000 + key_len)
    data = _fixed_bytes(64, seed=3100 + key_len)
    mac = hmac.new(key, data, "md5").digest()
    vectors = [
        {
            "id": "MD5_HMAC_basic",
            "type": "positive",
            "mechanism_name": "CKM_MD5_HMAC",
            "key_hex": key.hex(),
            "key_bits": key_len * 8,
            "input_hex": data.hex(),
            "mac_hex": mac.hex(),
        }
    ]
    return {
        "mechanism": "CKM_MD5_HMAC",
        "family": "hmac_md5",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def _i2b(n: int, length: int) -> str:
    """Convert integer to big-endian hex string of given byte length."""
    return n.to_bytes(length, "big").hex()


def generate_rsa_pkcs1_sha256() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv = key.private_numbers()
    pub = key.public_key().public_numbers()
    key_bytes = (pub.n.bit_length() + 7) // 8

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig = key.sign(msg, padding.PKCS1v15(), hashes.SHA256())
        vectors.append(
            {
                "id": f"rsa_pkcs1_sha256_{i}",
                "type": "positive",
                "mechanism_name": "CKM_SHA256_RSA_PKCS",
                "key_type": "asymmetric",
                "key_bits": 2048,
                "n_hex": _i2b(pub.n, key_bytes),
                "e_hex": _i2b(pub.e, (pub.e.bit_length() + 7) // 8),
                "d_hex": _i2b(priv.d, key_bytes),
                "p_hex": _i2b(priv.p, (priv.p.bit_length() + 7) // 8),
                "q_hex": _i2b(priv.q, (priv.q.bit_length() + 7) // 8),
                "dmp1_hex": _i2b(priv.dmp1, (priv.dmp1.bit_length() + 7) // 8),
                "dmq1_hex": _i2b(priv.dmq1, (priv.dmq1.bit_length() + 7) // 8),
                "iqmp_hex": _i2b(priv.iqmp, (priv.iqmp.bit_length() + 7) // 8),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_SHA256_RSA_PKCS",
        "family": "rsa_pkcs1_sha256",
        "key_type": "CKK_RSA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_rsa_pss_sha256() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv = key.private_numbers()
    pub = key.public_key().public_numbers()
    key_bytes = (pub.n.bit_length() + 7) // 8

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig = key.sign(
            msg,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=32,
            ),
            hashes.SHA256(),
        )
        vectors.append(
            {
                "id": f"rsa_pss_sha256_{i}",
                "type": "positive",
                "mechanism_name": "CKM_SHA256_RSA_PKCS_PSS",
                "key_type": "asymmetric",
                "key_bits": 2048,
                "n_hex": _i2b(pub.n, key_bytes),
                "e_hex": _i2b(pub.e, (pub.e.bit_length() + 7) // 8),
                "d_hex": _i2b(priv.d, key_bytes),
                "p_hex": _i2b(priv.p, (priv.p.bit_length() + 7) // 8),
                "q_hex": _i2b(priv.q, (priv.q.bit_length() + 7) // 8),
                "dmp1_hex": _i2b(priv.dmp1, (priv.dmp1.bit_length() + 7) // 8),
                "dmq1_hex": _i2b(priv.dmq1, (priv.dmq1.bit_length() + 7) // 8),
                "iqmp_hex": _i2b(priv.iqmp, (priv.iqmp.bit_length() + 7) // 8),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_SHA256_RSA_PKCS_PSS",
        "family": "rsa_pss_sha256",
        "key_type": "CKK_RSA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_sha256() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP256R1())
    priv_numbers = key.private_numbers()
    scalar_hex = _i2b(priv_numbers.private_value, 32)

    # P-256 curve OID in DER: OBJECT IDENTIFIER 1.2.840.10045.3.1.7
    ec_params_hex = "06082a8648ce3d030107"

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(32, "big") + s.to_bytes(32, "big")
        vectors.append(
            {
                "id": f"ecdsa_sha256_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA256",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA256",
        "family": "ecdsa_sha256",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_eddsa_ed25519() -> dict:
    from cryptography.hazmat.primitives.asymmetric import ed25519
    from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat

    # Ed25519 OID in DER: OBJECT IDENTIFIER 1.3.101.112
    ec_params_hex = "06032b6570"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7000)]
    vectors = []
    for i, msg in enumerate(messages):
        key = ed25519.Ed25519PrivateKey.generate()
        sig = key.sign(msg)
        # Extract raw 32-byte private scalar
        raw_priv = key.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())
        vectors.append(
            {
                "id": f"eddsa_ed25519_{i}",
                "type": "positive",
                "mechanism_name": "CKM_EDDSA",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": raw_priv.hex(),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_EDDSA",
        "family": "eddsa_ed25519",
        "key_type": "CKK_EC_EDWARDS",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_eddsa_ed448() -> dict:
    from cryptography.hazmat.primitives.asymmetric import ed448
    from cryptography.hazmat.primitives.serialization import Encoding, NoEncryption, PrivateFormat

    # Ed448 OID in DER: OBJECT IDENTIFIER 1.3.101.113
    ec_params_hex = "06032b6571"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7100)]
    vectors = []
    for i, msg in enumerate(messages):
        key = ed448.Ed448PrivateKey.generate()
        sig = key.sign(msg)
        # Extract raw 57-byte private key
        raw_priv = key.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption())
        vectors.append(
            {
                "id": f"eddsa_ed448_{i}",
                "type": "positive",
                "mechanism_name": "CKM_EDDSA",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": raw_priv.hex(),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_EDDSA",
        "family": "eddsa_ed448",
        "key_type": "CKK_EC_EDWARDS",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_rsa_pkcs1_sha1() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv = key.private_numbers()
    pub = key.public_key().public_numbers()
    key_bytes = (pub.n.bit_length() + 7) // 8

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig = key.sign(msg, padding.PKCS1v15(), hashes.SHA1())
        vectors.append(
            {
                "id": f"rsa_pkcs1_sha1_{i}",
                "type": "positive",
                "mechanism_name": "CKM_SHA1_RSA_PKCS",
                "key_type": "asymmetric",
                "key_bits": 2048,
                "n_hex": _i2b(pub.n, key_bytes),
                "e_hex": _i2b(pub.e, (pub.e.bit_length() + 7) // 8),
                "d_hex": _i2b(priv.d, key_bytes),
                "p_hex": _i2b(priv.p, (priv.p.bit_length() + 7) // 8),
                "q_hex": _i2b(priv.q, (priv.q.bit_length() + 7) // 8),
                "dmp1_hex": _i2b(priv.dmp1, (priv.dmp1.bit_length() + 7) // 8),
                "dmq1_hex": _i2b(priv.dmq1, (priv.dmq1.bit_length() + 7) // 8),
                "iqmp_hex": _i2b(priv.iqmp, (priv.iqmp.bit_length() + 7) // 8),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_SHA1_RSA_PKCS",
        "family": "rsa_pkcs1_sha1",
        "key_type": "CKK_RSA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_rsa_pkcs1_sha384() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv = key.private_numbers()
    pub = key.public_key().public_numbers()
    key_bytes = (pub.n.bit_length() + 7) // 8

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig = key.sign(msg, padding.PKCS1v15(), hashes.SHA384())
        vectors.append(
            {
                "id": f"rsa_pkcs1_sha384_{i}",
                "type": "positive",
                "mechanism_name": "CKM_SHA384_RSA_PKCS",
                "key_type": "asymmetric",
                "key_bits": 2048,
                "n_hex": _i2b(pub.n, key_bytes),
                "e_hex": _i2b(pub.e, (pub.e.bit_length() + 7) // 8),
                "d_hex": _i2b(priv.d, key_bytes),
                "p_hex": _i2b(priv.p, (priv.p.bit_length() + 7) // 8),
                "q_hex": _i2b(priv.q, (priv.q.bit_length() + 7) // 8),
                "dmp1_hex": _i2b(priv.dmp1, (priv.dmp1.bit_length() + 7) // 8),
                "dmq1_hex": _i2b(priv.dmq1, (priv.dmq1.bit_length() + 7) // 8),
                "iqmp_hex": _i2b(priv.iqmp, (priv.iqmp.bit_length() + 7) // 8),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_SHA384_RSA_PKCS",
        "family": "rsa_pkcs1_sha384",
        "key_type": "CKK_RSA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_rsa_pkcs1_sha512() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    priv = key.private_numbers()
    pub = key.public_key().public_numbers()
    key_bytes = (pub.n.bit_length() + 7) // 8

    messages = [b"", b"hello", b"A" * 245]
    vectors = []
    for i, msg in enumerate(messages):
        sig = key.sign(msg, padding.PKCS1v15(), hashes.SHA512())
        vectors.append(
            {
                "id": f"rsa_pkcs1_sha512_{i}",
                "type": "positive",
                "mechanism_name": "CKM_SHA512_RSA_PKCS",
                "key_type": "asymmetric",
                "key_bits": 2048,
                "n_hex": _i2b(pub.n, key_bytes),
                "e_hex": _i2b(pub.e, (pub.e.bit_length() + 7) // 8),
                "d_hex": _i2b(priv.d, key_bytes),
                "p_hex": _i2b(priv.p, (priv.p.bit_length() + 7) // 8),
                "q_hex": _i2b(priv.q, (priv.q.bit_length() + 7) // 8),
                "dmp1_hex": _i2b(priv.dmp1, (priv.dmp1.bit_length() + 7) // 8),
                "dmq1_hex": _i2b(priv.dmq1, (priv.dmq1.bit_length() + 7) // 8),
                "iqmp_hex": _i2b(priv.iqmp, (priv.iqmp.bit_length() + 7) // 8),
                "input_hex": msg.hex(),
                "signature_hex": sig.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_SHA512_RSA_PKCS",
        "family": "rsa_pkcs1_sha512",
        "key_type": "CKK_RSA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_p224() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP224R1())
    priv_numbers = key.private_numbers()
    scalar_size = 28
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06052b81040021"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7200)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA224()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_p224_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA224",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA224",
        "family": "ecdsa_p224",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_p384() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP384R1())
    priv_numbers = key.private_numbers()
    scalar_size = 48
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06052b81040022"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7300)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA384()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_p384_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA384",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA384",
        "family": "ecdsa_p384",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_p521() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP521R1())
    priv_numbers = key.private_numbers()
    scalar_size = 66
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06052b81040023"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7400)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA512()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_p521_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA512",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA512",
        "family": "ecdsa_p521",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_secp256k1() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP256K1())
    priv_numbers = key.private_numbers()
    scalar_size = 32
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06052b8104000a"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7500)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_secp256k1_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA256",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA256",
        "family": "ecdsa_secp256k1",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_brainpool256() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.BrainpoolP256R1())
    priv_numbers = key.private_numbers()
    scalar_size = 32
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06092b2403030208010107"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7600)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_brainpool256_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA256",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA256",
        "family": "ecdsa_brainpool256",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_brainpool384() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.BrainpoolP384R1())
    priv_numbers = key.private_numbers()
    scalar_size = 48
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06092b240303020801010b"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7700)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA384()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_brainpool384_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA384",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA384",
        "family": "ecdsa_brainpool384",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_brainpool512() -> dict:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.BrainpoolP512R1())
    priv_numbers = key.private_numbers()
    scalar_size = 64
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    ec_params_hex = "06092b240303020801010d"

    messages = [b"", b"hello", _fixed_bytes(100, seed=7800)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA512()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_brainpool512_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA512",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA512",
        "family": "ecdsa_brainpool512",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_ofb() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=4000 + bits)
        iv = _fixed_bytes(16, seed=4100 + bits)
        plaintext = _fixed_bytes(32, seed=4200 + bits)
        cipher = Cipher(algorithms.AES(key), modes.OFB(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_ofb_{bits}_32bytes",
                "type": "positive",
                "mechanism_name": "CKM_AES_OFB",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_OFB",
        "family": "aes_ofb",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_cfb128() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=4300 + bits)
        iv = _fixed_bytes(16, seed=4400 + bits)
        plaintext = _fixed_bytes(32, seed=4500 + bits)
        cipher = Cipher(algorithms.AES(key), modes.CFB(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_cfb128_{bits}_32bytes",
                "type": "positive",
                "mechanism_name": "CKM_AES_CFB128",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CFB128",
        "family": "aes_cfb128",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_cfb8() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=4600 + bits)
        iv = _fixed_bytes(16, seed=4700 + bits)
        plaintext = _fixed_bytes(32, seed=4800 + bits)
        cipher = Cipher(algorithms.AES(key), modes.CFB8(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_cfb8_{bits}_32bytes",
                "type": "positive",
                "mechanism_name": "CKM_AES_CFB8",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CFB8",
        "family": "aes_cfb8",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_camellia_ecb() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=5000 + bits)
        plaintext = _fixed_bytes(32, seed=5100 + bits)
        cipher = Cipher(algorithms.Camellia(key), modes.ECB())
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"camellia_ecb_{bits}_2blocks",
                "type": "positive",
                "mechanism_name": "CKM_CAMELLIA_ECB",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_CAMELLIA_ECB",
        "family": "camellia_ecb",
        "key_type": "CKK_CAMELLIA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_camellia_cbc() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=5200 + bits)
        iv = _fixed_bytes(16, seed=5300 + bits)
        plaintext = _fixed_bytes(32, seed=5400 + bits)
        cipher = Cipher(algorithms.Camellia(key), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"camellia_cbc_{bits}_2blocks",
                "type": "positive",
                "mechanism_name": "CKM_CAMELLIA_CBC",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_CAMELLIA_CBC",
        "family": "camellia_cbc",
        "key_type": "CKK_CAMELLIA",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_seed_ecb() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    # SEED has a fixed 128-bit key only
    key = _fixed_bytes(16, seed=5500)
    plaintext = _fixed_bytes(16, seed=5600)  # 1 block (SEED block size = 16 bytes)
    cipher = Cipher(algorithms.SEED(key), modes.ECB())
    enc = cipher.encryptor()
    ct = enc.update(plaintext) + enc.finalize()
    vectors = [
        {
            "id": "seed_ecb_128_1block",
            "type": "positive",
            "mechanism_name": "CKM_SEED_ECB",
            "key_type": "symmetric",
            "key_bits": 128,
            "key_hex": key.hex(),
            "params": {},
            "plaintext_hex": plaintext.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SEED_ECB",
        "family": "seed_ecb",
        "key_type": "CKK_SEED",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_seed_cbc() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    # SEED has a fixed 128-bit key only
    key = _fixed_bytes(16, seed=5700)
    iv = _fixed_bytes(16, seed=5800)
    plaintext = _fixed_bytes(16, seed=5900)  # 1 block
    cipher = Cipher(algorithms.SEED(key), modes.CBC(iv))
    enc = cipher.encryptor()
    ct = enc.update(plaintext) + enc.finalize()
    vectors = [
        {
            "id": "seed_cbc_128_1block",
            "type": "positive",
            "mechanism_name": "CKM_SEED_CBC",
            "key_type": "symmetric",
            "key_bits": 128,
            "key_hex": key.hex(),
            "params": {"iv_hex": iv.hex()},
            "plaintext_hex": plaintext.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_SEED_CBC",
        "family": "seed_cbc",
        "key_type": "CKK_SEED",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def _openssl_evp_setup(libcrypto: object) -> bool:
    """Set up argtypes/restype on OpenSSL EVP functions to avoid ctypes marshalling segfaults."""
    import ctypes

    libcrypto.EVP_CIPHER_CTX_new.restype = ctypes.c_void_p
    libcrypto.EVP_CIPHER_CTX_new.argtypes = []

    libcrypto.EVP_CIPHER_CTX_free.restype = None
    libcrypto.EVP_CIPHER_CTX_free.argtypes = [ctypes.c_void_p]

    libcrypto.EVP_get_cipherbyname.restype = ctypes.c_void_p
    libcrypto.EVP_get_cipherbyname.argtypes = [ctypes.c_char_p]

    libcrypto.EVP_EncryptInit_ex.restype = ctypes.c_int
    libcrypto.EVP_EncryptInit_ex.argtypes = [
        ctypes.c_void_p,  # ctx
        ctypes.c_void_p,  # cipher
        ctypes.c_void_p,  # engine (NULL)
        ctypes.c_char_p,  # key
        ctypes.c_char_p,  # iv
    ]

    libcrypto.EVP_CIPHER_CTX_set_padding.restype = ctypes.c_int
    libcrypto.EVP_CIPHER_CTX_set_padding.argtypes = [ctypes.c_void_p, ctypes.c_int]

    libcrypto.EVP_EncryptUpdate.restype = ctypes.c_int
    libcrypto.EVP_EncryptUpdate.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_int),
        ctypes.c_char_p,
        ctypes.c_int,
    ]

    libcrypto.EVP_EncryptFinal_ex.restype = ctypes.c_int
    libcrypto.EVP_EncryptFinal_ex.argtypes = [
        ctypes.c_void_p,
        ctypes.c_char_p,
        ctypes.POINTER(ctypes.c_int),
    ]
    return True


def _openssl_encrypt(
    libcrypto: object,
    cipher_name: bytes,
    key: bytes,
    iv: bytes | None,
    plaintext: bytes,
) -> bytes:
    """Encrypt plaintext using an OpenSSL EVP cipher (no padding, block-aligned input)."""
    import ctypes

    cipher = libcrypto.EVP_get_cipherbyname(cipher_name)
    if not cipher:
        return b""
    ctx = libcrypto.EVP_CIPHER_CTX_new()
    try:
        libcrypto.EVP_EncryptInit_ex(ctx, cipher, None, key, iv)
        libcrypto.EVP_CIPHER_CTX_set_padding(ctx, 0)
        outbuf = ctypes.create_string_buffer(len(plaintext) + 16)
        outlen = ctypes.c_int(0)
        libcrypto.EVP_EncryptUpdate(
            ctx, outbuf, ctypes.byref(outlen), plaintext, len(plaintext)
        )
        total = outlen.value
        libcrypto.EVP_EncryptFinal_ex(
            ctx,
            ctypes.cast(ctypes.addressof(outbuf) + total, ctypes.c_char_p),
            ctypes.byref(outlen),
        )
        total += outlen.value
        return outbuf.raw[:total]
    finally:
        libcrypto.EVP_CIPHER_CTX_free(ctx)


def generate_aria_ecb() -> dict:
    """ARIA ECB vectors via OpenSSL EVP (ctypes)."""
    import ctypes
    import ctypes.util

    libcrypto_path = ctypes.util.find_library("crypto")
    if not libcrypto_path:
        return {
            "mechanism": "CKM_ARIA_ECB",
            "family": "aria_ecb",
            "key_type": "CKK_ARIA",
            "source": "skipped: libcrypto not found",
            "vectors": [],
        }

    libcrypto = ctypes.CDLL(libcrypto_path)
    _openssl_evp_setup(libcrypto)

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=6000 + bits)
        pt = _fixed_bytes(32, seed=6100 + bits)  # 2 blocks
        cipher_name = f"aria-{bits}-ecb".encode()
        ct = _openssl_encrypt(libcrypto, cipher_name, key, None, pt)
        if not ct:
            continue
        vectors.append(
            {
                "id": f"aria_ecb_{bits}",
                "type": "positive",
                "mechanism_name": "CKM_ARIA_ECB",
                "key_type": "symmetric",
                "key_hex": key.hex(),
                "key_bits": bits,
                "plaintext_hex": pt.hex(),
                "ciphertext_hex": ct.hex(),
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ARIA_ECB",
        "family": "aria_ecb",
        "key_type": "CKK_ARIA",
        "source": "generated via OpenSSL EVP ctypes",
        "vectors": vectors,
    }


def generate_des_ecb() -> dict:
    """DES-ECB (single DES) vectors.

    Single DES is not in the cryptography library as a public API; DES in
    OpenSSL 3 requires the legacy provider.  We compute single-DES by
    instantiating TripleDES with K1=K2=K3 (the 8-byte key repeated 3 times),
    which is mathematically equivalent to single DES and produces identical
    output.  Only the 8-byte key is stored in the JSON — it is what PKCS#11
    hardware receives for CKM_DES_ECB.

    DES key = 8 bytes (56-bit effective), block = 8 bytes.
    """
    from cryptography.hazmat.decrepit.ciphers.algorithms import TripleDES
    from cryptography.hazmat.primitives.ciphers import Cipher, modes

    key8 = _fixed_bytes(8, seed=8000)  # 8-byte DES key
    key24 = key8 * 3  # K1=K2=K3 → equivalent to single DES
    pt = _fixed_bytes(16, seed=8100)  # 2 DES blocks (8 bytes each)
    cipher = Cipher(TripleDES(key24), modes.ECB())
    enc = cipher.encryptor()
    ct = enc.update(pt) + enc.finalize()
    vectors = [
        {
            "id": "des_ecb_64_2blocks",
            "type": "positive",
            "mechanism_name": "CKM_DES_ECB",
            "key_type": "symmetric",
            "key_bits": 64,
            "key_hex": key8.hex(),
            "params": {},
            "plaintext_hex": pt.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_DES_ECB",
        "family": "des_ecb",
        "key_type": "CKK_DES",
        "source": "generated by scripts/generate_mechanism_vectors.py (TripleDES K1=K2=K3)",
        "vectors": vectors,
    }


def generate_des_cbc() -> dict:
    """DES-CBC (single DES) vectors.

    Uses TripleDES with K1=K2=K3 to compute single-DES ciphertext; only the
    8-byte key is stored for use with CKM_DES_CBC.
    DES key = 8 bytes, IV = 8 bytes, block = 8 bytes.
    """
    from cryptography.hazmat.decrepit.ciphers.algorithms import TripleDES
    from cryptography.hazmat.primitives.ciphers import Cipher, modes

    key8 = _fixed_bytes(8, seed=8200)  # 8-byte DES key
    key24 = key8 * 3  # K1=K2=K3
    iv = _fixed_bytes(8, seed=8300)  # 8-byte DES IV
    pt = _fixed_bytes(16, seed=8400)  # 2 DES blocks
    cipher = Cipher(TripleDES(key24), modes.CBC(iv))
    enc = cipher.encryptor()
    ct = enc.update(pt) + enc.finalize()
    vectors = [
        {
            "id": "des_cbc_64_2blocks",
            "type": "positive",
            "mechanism_name": "CKM_DES_CBC",
            "key_type": "symmetric",
            "key_bits": 64,
            "key_hex": key8.hex(),
            "params": {"iv_hex": iv.hex()},
            "plaintext_hex": pt.hex(),
            "ciphertext_hex": ct.hex(),
        }
    ]
    return {
        "mechanism": "CKM_DES_CBC",
        "family": "des_cbc",
        "key_type": "CKK_DES",
        "source": "generated by scripts/generate_mechanism_vectors.py (TripleDES K1=K2=K3)",
        "vectors": vectors,
    }


def generate_aes_ccm() -> dict:
    """AES-CCM vectors using the cryptography library AESCCM.

    3 key sizes (128/192/256), 7-byte nonce (typical CCM), 16-byte tag, with AAD.
    params: {iv_hex, aad_hex, tag_bits, data_len}
    """
    from cryptography.hazmat.primitives.ciphers.aead import AESCCM

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=8500 + bits)
        nonce = _fixed_bytes(7, seed=8600 + bits)  # 7-byte nonce is common for CCM
        plaintext = _fixed_bytes(32, seed=8700 + bits)
        aad = _fixed_bytes(16, seed=8800 + bits)
        aesccm = AESCCM(key, tag_length=16)
        # ct includes 16-byte tag appended
        ct_tag = aesccm.encrypt(nonce, plaintext, aad)
        ct = ct_tag[:-16]
        tag = ct_tag[-16:]
        vectors.append(
            {
                "id": f"aes_ccm_{bits}_with_aad",
                "type": "positive",
                "mechanism_name": "CKM_AES_CCM",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {
                    "iv_hex": nonce.hex(),
                    "aad_hex": aad.hex(),
                    "tag_bits": 128,
                    "data_len": len(plaintext),
                },
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
                "tag_hex": tag.hex(),
            }
        )
        # Also without AAD
        ct_tag2 = aesccm.encrypt(nonce, plaintext, None)
        vectors.append(
            {
                "id": f"aes_ccm_{bits}_no_aad",
                "type": "positive",
                "mechanism_name": "CKM_AES_CCM",
                "key_type": "symmetric",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {
                    "iv_hex": nonce.hex(),
                    "aad_hex": "",
                    "tag_bits": 128,
                    "data_len": len(plaintext),
                },
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct_tag2[:-16].hex(),
                "tag_hex": ct_tag2[-16:].hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CCM",
        "family": "aes_ccm",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_chacha20_poly1305() -> dict:
    """ChaCha20-Poly1305 AEAD vector.

    Fixed 256-bit key, 12-byte nonce; ciphertext includes 16-byte Poly1305 tag.
    params: {iv_hex, aad_hex, tag_bits: 128}
    """
    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

    key = _fixed_bytes(32, seed=8900)  # 256-bit key
    nonce = _fixed_bytes(12, seed=9000)  # 12-byte nonce (RFC 8439)
    plaintext = _fixed_bytes(32, seed=9100)
    aad = _fixed_bytes(16, seed=9200)
    chacha = ChaCha20Poly1305(key)
    # ct includes 16-byte Poly1305 tag
    ct_tag = chacha.encrypt(nonce, plaintext, aad)
    ct = ct_tag[:-16]
    tag = ct_tag[-16:]
    vectors = [
        {
            "id": "chacha20_poly1305_256_with_aad",
            "type": "positive",
            "mechanism_name": "CKM_CHACHA20_POLY1305",
            "key_type": "symmetric",
            "key_bits": 256,
            "key_hex": key.hex(),
            "params": {"iv_hex": nonce.hex(), "aad_hex": aad.hex(), "tag_bits": 128},
            "plaintext_hex": plaintext.hex(),
            "ciphertext_hex": ct.hex(),
            "tag_hex": tag.hex(),
        }
    ]
    return {
        "mechanism": "CKM_CHACHA20_POLY1305",
        "family": "chacha20_poly1305",
        "key_type": "CKK_CHACHA20",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_ecdsa_sha1() -> dict:
    """ECDSA-SHA1 vectors on P-256 (secp256r1).

    verify_only=True: the test imports the fixed key and verifies the signature.
    """
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    key = ec.generate_private_key(ec.SECP256R1())
    priv_numbers = key.private_numbers()
    scalar_size = 32
    scalar_hex = _i2b(priv_numbers.private_value, scalar_size)
    # P-256 OID in DER: OBJECT IDENTIFIER 1.2.840.10045.3.1.7
    ec_params_hex = "06082a8648ce3d030107"

    messages = [b"", b"hello", _fixed_bytes(100, seed=9300)]
    vectors = []
    for i, msg in enumerate(messages):
        sig_der = key.sign(msg, ec.ECDSA(hashes.SHA1()))
        r, s = decode_dss_signature(sig_der)
        sig_p11 = r.to_bytes(scalar_size, "big") + s.to_bytes(scalar_size, "big")
        vectors.append(
            {
                "id": f"ecdsa_sha1_{i}",
                "type": "positive",
                "mechanism_name": "CKM_ECDSA_SHA1",
                "key_type": "asymmetric",
                "ec_params_hex": ec_params_hex,
                "ec_private_scalar_hex": scalar_hex,
                "input_hex": msg.hex(),
                "signature_hex": sig_p11.hex(),
                "verify_only": True,
                "params": {},
            }
        )
    return {
        "mechanism": "CKM_ECDSA_SHA1",
        "family": "ecdsa_sha1",
        "key_type": "CKK_EC",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


# AES-XTS: deferred — requires CK_AES_XTS_PARAMS tweak handling (dual-key, per-sector tweak)


def generate_aria_cbc() -> dict:
    """ARIA CBC vectors via OpenSSL EVP (ctypes)."""
    import ctypes
    import ctypes.util

    libcrypto_path = ctypes.util.find_library("crypto")
    if not libcrypto_path:
        return {
            "mechanism": "CKM_ARIA_CBC",
            "family": "aria_cbc",
            "key_type": "CKK_ARIA",
            "source": "skipped: libcrypto not found",
            "vectors": [],
        }

    libcrypto = ctypes.CDLL(libcrypto_path)
    _openssl_evp_setup(libcrypto)

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=6200 + bits)
        iv = _fixed_bytes(16, seed=6300 + bits)
        pt = _fixed_bytes(32, seed=6400 + bits)  # 2 blocks
        cipher_name = f"aria-{bits}-cbc".encode()
        ct = _openssl_encrypt(libcrypto, cipher_name, key, iv, pt)
        if not ct:
            continue
        vectors.append(
            {
                "id": f"aria_cbc_{bits}",
                "type": "positive",
                "mechanism_name": "CKM_ARIA_CBC",
                "key_type": "symmetric",
                "key_hex": key.hex(),
                "key_bits": bits,
                "plaintext_hex": pt.hex(),
                "ciphertext_hex": ct.hex(),
                "params": {"iv_hex": iv.hex()},
            }
        )
    return {
        "mechanism": "CKM_ARIA_CBC",
        "family": "aria_cbc",
        "key_type": "CKK_ARIA",
        "source": "generated via OpenSSL EVP ctypes",
        "vectors": vectors,
    }


GENERATORS = {
    "aes_ecb": generate_aes_ecb,
    "aes_cbc": generate_aes_cbc,
    "aes_gcm": generate_aes_gcm,
    "sha": generate_sha,
    "hmac": generate_hmac,
    "aes_cbc_pad": generate_aes_cbc_pad,
    "aes_ctr": generate_aes_ctr,
    "des3_ecb": generate_des3_ecb,
    "des3_cbc": generate_des3_cbc,
    "hmac_sha256": generate_hmac_sha256,
    "hmac_sha384": generate_hmac_sha384,
    "hmac_sha512": generate_hmac_sha512,
    "rsa_pkcs1_sha256": generate_rsa_pkcs1_sha256,
    "rsa_pss_sha256": generate_rsa_pss_sha256,
    "ecdsa_sha256": generate_ecdsa_sha256,
    "eddsa_ed25519": generate_eddsa_ed25519,
    "eddsa_ed448": generate_eddsa_ed448,
    "rsa_pkcs1_sha1": generate_rsa_pkcs1_sha1,
    "rsa_pkcs1_sha384": generate_rsa_pkcs1_sha384,
    "rsa_pkcs1_sha512": generate_rsa_pkcs1_sha512,
    "ecdsa_p224": generate_ecdsa_p224,
    "ecdsa_p384": generate_ecdsa_p384,
    "ecdsa_p521": generate_ecdsa_p521,
    "ecdsa_secp256k1": generate_ecdsa_secp256k1,
    "ecdsa_brainpool256": generate_ecdsa_brainpool256,
    "ecdsa_brainpool384": generate_ecdsa_brainpool384,
    "ecdsa_brainpool512": generate_ecdsa_brainpool512,
    "sha3": generate_sha3,
    "sha512_truncated": generate_sha512_truncated,
    "hmac_sha1": generate_hmac_sha1,
    "hmac_sha224": generate_hmac_sha224,
    "hmac_md5": generate_hmac_md5,
    "aes_ofb": generate_aes_ofb,
    "aes_cfb128": generate_aes_cfb128,
    "aes_cfb8": generate_aes_cfb8,
    "camellia_ecb": generate_camellia_ecb,
    "camellia_cbc": generate_camellia_cbc,
    "seed_ecb": generate_seed_ecb,
    "seed_cbc": generate_seed_cbc,
    "aria_ecb": generate_aria_ecb,
    "aria_cbc": generate_aria_cbc,
    "des_ecb": generate_des_ecb,
    "des_cbc": generate_des_cbc,
    "aes_ccm": generate_aes_ccm,
    "chacha20_poly1305": generate_chacha20_poly1305,
    "ecdsa_sha1": generate_ecdsa_sha1,
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate mechanism KAT vectors")
    parser.add_argument("--all", action="store_true", help="Generate all families")
    parser.add_argument("--family", type=str, help="Generate specific family")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.all:
        families = list(GENERATORS.keys())
    elif args.family:
        families = [args.family]
    else:
        parser.print_help()
        sys.exit(1)

    for family in families:
        gen = GENERATORS.get(family)
        if gen is None:
            print(f"Unknown family: {family}", file=sys.stderr)
            continue
        data = gen()
        path = OUTPUT_DIR / f"{family}.json"
        path.write_text(json.dumps(data, indent=2) + "\n")
        print(f"Generated {path} ({len(data['vectors'])} vectors)")


if __name__ == "__main__":
    main()
