#!/usr/bin/env python3
"""Generate PKCS#11 mechanism KAT vectors using the cryptography library.

Usage:
    uv run python scripts/generate_mechanism_vectors.py --all
    uv run python scripts/generate_mechanism_vectors.py --family aes_ecb
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

OUTPUT_DIR = Path("src/pkcs11_check/testcases/data/mechanism_vectors")


def _fixed_bytes(n: int, seed: int = 42) -> bytes:
    """Deterministic bytes for reproducible vectors."""
    import hashlib

    result = b""
    counter = seed
    while len(result) < n:
        result += hashlib.sha256(counter.to_bytes(8, "big")).digest()
        counter += 1
    return result[:n]


def generate_aes_ecb() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=100 + bits)
        plaintext = _fixed_bytes(32, seed=200 + bits)  # 2 blocks
        cipher = Cipher(algorithms.AES(key), modes.ECB())
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_ecb_{bits}_2blocks",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_ECB",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_cbc() -> dict:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=300 + bits)
        iv = _fixed_bytes(16, seed=400 + bits)
        plaintext = _fixed_bytes(32, seed=500 + bits)
        cipher = Cipher(algorithms.AES(key), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(plaintext) + enc.finalize()
        vectors.append(
            {
                "id": f"aes_cbc_{bits}_2blocks",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex()},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_CBC",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_aes_gcm() -> dict:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    vectors = []
    for bits in (128, 192, 256):
        key = _fixed_bytes(bits // 8, seed=600 + bits)
        iv = _fixed_bytes(12, seed=700 + bits)
        plaintext = _fixed_bytes(32, seed=800 + bits)
        aad = _fixed_bytes(16, seed=900 + bits)
        aesgcm = AESGCM(key)
        ct_tag = aesgcm.encrypt(iv, plaintext, aad)
        ct = ct_tag[:-16]
        tag = ct_tag[-16:]
        vectors.append(
            {
                "id": f"aes_gcm_{bits}_with_aad",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex(), "aad_hex": aad.hex(), "tag_bits": 128},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct.hex(),
                "tag_hex": tag.hex(),
            }
        )
        # Also without AAD
        ct_tag2 = aesgcm.encrypt(iv, plaintext, None)
        vectors.append(
            {
                "id": f"aes_gcm_{bits}_no_aad",
                "type": "positive",
                "key_bits": bits,
                "key_hex": key.hex(),
                "params": {"iv_hex": iv.hex(), "aad_hex": "", "tag_bits": 128},
                "plaintext_hex": plaintext.hex(),
                "ciphertext_hex": ct_tag2[:-16].hex(),
                "tag_hex": ct_tag2[-16:].hex(),
            }
        )
    return {
        "mechanism": "CKM_AES_GCM",
        "family": "aes",
        "key_type": "CKK_AES",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_sha() -> dict:
    import hashlib

    vectors = []
    test_inputs = [
        ("empty", b""),
        ("abc", b"abc"),
        ("long", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
    ]
    for algo, name, digest_len in [
        ("sha1", "SHA_1", 20),
        ("sha224", "SHA224", 28),
        ("sha256", "SHA256", 32),
        ("sha384", "SHA384", 48),
        ("sha512", "SHA512", 64),
    ]:
        for input_id, input_data in test_inputs:
            h = hashlib.new(algo)
            h.update(input_data)
            vectors.append(
                {
                    "id": f"{name}_{input_id}",
                    "type": "positive",
                    "mechanism_name": f"CKM_{name}",
                    "input_hex": input_data.hex(),
                    "digest_hex": h.hexdigest(),
                    "digest_len": digest_len,
                }
            )
    return {
        "mechanism": "CKM_SHA_*",
        "family": "sha",
        "key_type": None,
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


def generate_hmac() -> dict:
    import hmac

    vectors = []
    for algo, name, key_len in [
        ("sha256", "SHA256_HMAC", 32),
        ("sha384", "SHA384_HMAC", 48),
        ("sha512", "SHA512_HMAC", 64),
    ]:
        key = _fixed_bytes(key_len, seed=1000 + key_len)
        data = _fixed_bytes(64, seed=1100 + key_len)
        mac = hmac.new(key, data, algo).digest()
        vectors.append(
            {
                "id": f"{name}_basic",
                "type": "positive",
                "mechanism_name": f"CKM_{name}",
                "key_hex": key.hex(),
                "key_bits": key_len * 8,
                "input_hex": data.hex(),
                "mac_hex": mac.hex(),
            }
        )
    return {
        "mechanism": "CKM_SHA*_HMAC",
        "family": "hmac",
        "key_type": "CKK_GENERIC_SECRET",
        "source": "generated by scripts/generate_mechanism_vectors.py",
        "vectors": vectors,
    }


GENERATORS = {
    "aes_ecb": generate_aes_ecb,
    "aes_cbc": generate_aes_cbc,
    "aes_gcm": generate_aes_gcm,
    "sha": generate_sha,
    "hmac": generate_hmac,
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate mechanism KAT vectors")
    parser.add_argument("--all", action="store_true", help="Generate all families")
    parser.add_argument("--family", type=str, help="Generate specific family")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.all:
        families = list(GENERATORS.keys())
    elif args.family:
        families = [args.family]
    else:
        parser.print_help()
        sys.exit(1)

    for family in families:
        gen = GENERATORS.get(family)
        if gen is None:
            print(f"Unknown family: {family}", file=sys.stderr)
            continue
        data = gen()
        path = OUTPUT_DIR / f"{family}.json"
        path.write_text(json.dumps(data, indent=2) + "\n")
        print(f"Generated {path} ({len(data['vectors'])} vectors)")


if __name__ == "__main__":
    main()
