"""Extended cross-verification tests.

Cross-verifies PKCS#11 operations against the Python cryptography library
for operations not covered in test_crossverify.py: AES-CBC, AES-GCM,
RSA-OAEP encrypt/decrypt, and RSA-PSS sign/verify.
"""

from __future__ import annotations

from typing import Any

import pytest
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding as rsa_padding
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from pkcs11 import Attribute, KeyType, Mechanism
from pkcs11.mechanisms import MGF

from p11test.testcases.conftest import has_mechanism, import_aes_key

pytestmark = pytest.mark.crossverify


class TestAESCBCCrossVerify:
    """Cross-verify AES-CBC against cryptography library."""

    def test_aes_cbc_encrypt_crossverify(self, p11_session: Any) -> None:
        """AES-CBC encryption matches cryptography library output."""
        key_bytes = bytes(range(32))
        iv = bytes(range(16))
        data = b"\xaa" * 64  # 4 blocks

        # PKCS#11
        p11_key = import_aes_key(p11_session, key_bytes)
        ct_p11 = p11_key.encrypt(data, mechanism=Mechanism.AES_CBC, mechanism_param=iv)

        # cryptography
        cipher = Cipher(algorithms.AES(key_bytes), modes.CBC(iv))
        enc = cipher.encryptor()
        ct_crypto = enc.update(data) + enc.finalize()

        assert ct_p11 == ct_crypto

    def test_aes_cbc_decrypt_crossverify(self, p11_session: Any) -> None:
        """AES-CBC decryption of cryptography-generated ciphertext works."""
        key_bytes = bytes(range(32))
        iv = b"\x00" * 16
        data = b"\xbb" * 48

        # Encrypt with cryptography
        cipher = Cipher(algorithms.AES(key_bytes), modes.CBC(iv))
        enc = cipher.encryptor()
        ct = enc.update(data) + enc.finalize()

        # Decrypt with PKCS#11
        p11_key = import_aes_key(p11_session, key_bytes)
        pt = p11_key.decrypt(ct, mechanism=Mechanism.AES_CBC, mechanism_param=iv)
        assert pt == data


class TestAESGCMCrossVerify:
    """Cross-verify AES-GCM against cryptography library."""

    def test_aes_gcm_decrypt_crossverify(self, p11_session: Any, p11_module: Any) -> None:
        """Decrypt ciphertext generated by cryptography library."""
        if not has_mechanism(p11_module, "AES_GCM"):
            pytest.skip("CKM_AES_GCM not supported")

        key_bytes = bytes(range(32))
        plaintext = b"AES-GCM cross-verify test data!!"
        iv = bytes(range(12))  # 96-bit nonce

        # Encrypt with cryptography
        aesgcm = AESGCM(key_bytes)
        ct_tag = aesgcm.encrypt(iv, plaintext, None)
        # ct_tag = ciphertext || tag (16 bytes)

        # Decrypt with PKCS#11
        p11_key = import_aes_key(p11_session, key_bytes)
        try:
            pt = p11_key.decrypt(ct_tag, mechanism=Mechanism.AES_GCM, mechanism_param=iv)
            assert pt == plaintext
        except Exception:
            # Some modules need different GCM parameter format
            pytest.skip("AES-GCM parameter format incompatible")


class TestRSAPSSCrossVerify:
    """Cross-verify RSA-PSS against cryptography library."""

    def test_rsa_pss_sign_p11_verify_crypto(self, p11_session: Any, p11_module: Any) -> None:
        """Sign with PKCS#11 RSA-PSS, verify with cryptography."""
        if not has_mechanism(p11_module, "SHA256_RSA_PKCS_PSS"):
            pytest.skip("RSA-PSS not supported")

        pub, priv = p11_session.generate_keypair(KeyType.RSA, 2048)

        data = b"RSA-PSS cross-verify test"
        pss_params = (Mechanism.SHA256, MGF.SHA256, 32)
        sig = priv.sign(data, mechanism=Mechanism.SHA256_RSA_PKCS_PSS, mechanism_param=pss_params)

        # Export public key components
        modulus = pub[Attribute.MODULUS]
        exponent = pub[Attribute.PUBLIC_EXPONENT]

        # Reconstruct public key in cryptography
        n = int.from_bytes(modulus, "big")
        e = int.from_bytes(exponent, "big")
        crypto_pub = rsa.RSAPublicNumbers(e, n).public_key()

        # Verify with cryptography (PSS with SHA-256)
        try:
            crypto_pub.verify(
                sig,
                data,
                rsa_padding.PSS(
                    mgf=rsa_padding.MGF1(hashes.SHA256()),
                    salt_length=rsa_padding.PSS.AUTO,
                ),
                hashes.SHA256(),
            )
        except Exception:
            pytest.fail("cryptography failed to verify PKCS#11 RSA-PSS signature")


class TestRSAOAEPCrossVerify:
    """Cross-verify RSA-OAEP against cryptography library."""

    def test_rsa_oaep_encrypt_p11_decrypt_crypto(self, p11_session: Any, p11_module: Any) -> None:
        """Encrypt with PKCS#11 RSA-OAEP, decrypt with cryptography."""
        if not has_mechanism(p11_module, "RSA_PKCS_OAEP"):
            pytest.skip("RSA-OAEP not supported")

        pub, priv = p11_session.generate_keypair(
            KeyType.RSA,
            2048,
            private_template={
                Attribute.SENSITIVE: False,
                Attribute.EXTRACTABLE: True,
            },
        )

        plaintext = b"OAEP cross-verify"
        ct = pub.encrypt(plaintext, mechanism=Mechanism.RSA_PKCS_OAEP)

        # Export private key components for cryptography
        modulus = priv[Attribute.MODULUS]
        pub_exp = priv[Attribute.PUBLIC_EXPONENT]
        priv_exp = priv[Attribute.PRIVATE_EXPONENT]
        p = priv[Attribute.PRIME_1]
        q = priv[Attribute.PRIME_2]
        dp = priv[Attribute.EXPONENT_1]
        dq = priv[Attribute.EXPONENT_2]
        qi = priv[Attribute.COEFFICIENT]

        n = int.from_bytes(modulus, "big")
        e = int.from_bytes(pub_exp, "big")
        d = int.from_bytes(priv_exp, "big")
        p_int = int.from_bytes(p, "big")
        q_int = int.from_bytes(q, "big")
        dp_int = int.from_bytes(dp, "big")
        dq_int = int.from_bytes(dq, "big")
        qi_int = int.from_bytes(qi, "big")

        crypto_priv = rsa.RSAPrivateNumbers(
            p_int,
            q_int,
            d,
            dp_int,
            dq_int,
            qi_int,
            rsa.RSAPublicNumbers(e, n),
        ).private_key()

        # Decrypt with cryptography (OAEP SHA-1, default for PKCS#11)
        pt = crypto_priv.decrypt(
            ct,
            rsa_padding.OAEP(
                mgf=rsa_padding.MGF1(algorithm=hashes.SHA1()),
                algorithm=hashes.SHA1(),
                label=None,
            ),
        )
        assert pt == plaintext
