"""Curated attribute value type metadata per OASIS PKCS#11 v3.2 spec.

This is NOT generated from C headers (headers don't contain type info).
It is manually maintained from the OASIS spec attribute tables and
cross-checked against python-pkcs11/pkcs11/attributes.py in tests.

Edit this file directly when adding new attributes or fixing types.
"""

from __future__ import annotations

from .types_std import (
    # Common object attributes
    CKA_AC_ISSUER,
    CKA_ALLOWED_MECHANISMS,
    CKA_ALWAYS_AUTHENTICATE,
    CKA_ALWAYS_SENSITIVE,
    CKA_APPLICATION,
    CKA_ATTR_TYPES,
    CKA_BASE,
    CKA_CERTIFICATE_CATEGORY,
    CKA_CERTIFICATE_TYPE,
    CKA_CHECK_VALUE,
    CKA_CLASS,
    CKA_COEFFICIENT,
    CKA_COPYABLE,
    CKA_DECAPSULATE,
    CKA_DECAPSULATE_TEMPLATE,
    CKA_DECRYPT,
    CKA_DERIVE,
    CKA_DERIVE_TEMPLATE,
    CKA_DESTROYABLE,
    CKA_EC_PARAMS,
    CKA_EC_POINT,
    CKA_ENCAPSULATE,
    CKA_ENCAPSULATE_TEMPLATE,
    CKA_ENCRYPT,
    CKA_END_DATE,
    CKA_EXPONENT_1,
    CKA_EXPONENT_2,
    CKA_EXTRACTABLE,
    CKA_GOSTR3410_PARAMS,
    CKA_GOSTR3411_PARAMS,
    CKA_HASH_OF_CERTIFICATE,
    CKA_HASH_OF_ISSUER_PUBLIC_KEY,
    CKA_HASH_OF_SUBJECT_PUBLIC_KEY,
    CKA_HSS_KEYS_REMAINING,
    CKA_HSS_LEVELS,
    CKA_HSS_LMS_TYPE,
    CKA_HSS_LMS_TYPES,
    CKA_HSS_LMOTS_TYPE,
    CKA_HSS_LMOTS_TYPES,
    CKA_ID,
    CKA_ISSUER,
    CKA_JAVA_MIDP_SECURITY_DOMAIN,
    CKA_KEY_GEN_MECHANISM,
    CKA_KEY_TYPE,
    CKA_LABEL,
    CKA_LOCAL,
    CKA_MECHANISM_TYPE,
    CKA_MODIFIABLE,
    CKA_MODULUS,
    CKA_MODULUS_BITS,
    CKA_NAME_HASH_ALGORITHM,
    CKA_NEVER_EXTRACTABLE,
    CKA_OBJECT_ID,
    CKA_OBJECT_VALIDATION_FLAGS,
    CKA_OWNER,
    CKA_PARAMETER_SET,
    CKA_PRIME,
    CKA_PRIME_1,
    CKA_PRIME_2,
    CKA_PRIME_BITS,
    CKA_PRIVATE,
    CKA_PRIVATE_EXPONENT,
    CKA_PROFILE_ID,
    CKA_PUBLIC_CRC64_VALUE,
    CKA_PUBLIC_EXPONENT,
    CKA_PUBLIC_KEY_INFO,
    CKA_SEED,
    CKA_SENSITIVE,
    CKA_SERIAL_NUMBER,
    CKA_SIGN,
    CKA_SIGN_RECOVER,
    CKA_START_DATE,
    CKA_SUBJECT,
    CKA_SUBPRIME,
    CKA_SUBPRIME_BITS,
    CKA_TOKEN,
    CKA_TRUSTED,
    CKA_UNIQUE_ID,
    CKA_UNWRAP,
    CKA_UNWRAP_TEMPLATE,
    CKA_URL,
    CKA_VALIDATION_AUTHORITY_TYPE,
    CKA_VALIDATION_CERTIFICATE_IDENTIFIER,
    CKA_VALIDATION_CERTIFICATE_URI,
    CKA_VALIDATION_COUNTRY,
    CKA_VALIDATION_FLAG,
    CKA_VALIDATION_LEVEL,
    CKA_VALIDATION_MODULE_ID,
    CKA_VALIDATION_PROFILE,
    CKA_VALIDATION_TYPE,
    CKA_VALIDATION_VENDOR_URI,
    CKA_VALIDATION_VERSION,
    CKA_VENDOR_DEFINED,
    # Deprecated / legacy
    CKA_AUTH_PIN_FLAGS,
    CKA_SECONDARY_AUTH,
    # OTP attributes
    CKA_OTP_CHALLENGE_REQUIREMENT,
    CKA_OTP_COUNTER,
    CKA_OTP_COUNTER_REQUIREMENT,
    CKA_OTP_FORMAT,
    CKA_OTP_LENGTH,
    CKA_OTP_PIN_REQUIREMENT,
    CKA_OTP_SERVICE_IDENTIFIER,
    CKA_OTP_SERVICE_LOGO,
    CKA_OTP_SERVICE_LOGO_TYPE,
    CKA_OTP_TIME,
    CKA_OTP_TIME_INTERVAL,
    CKA_OTP_TIME_REQUIREMENT,
    CKA_OTP_USER_FRIENDLY_MODE,
    CKA_OTP_USER_IDENTIFIER,
    # GOST
    CKA_GOST28147_PARAMS,
    # Hardware feature / display
    CKA_BITS_PER_PIXEL,
    CKA_CHAR_COLUMNS,
    CKA_CHAR_ROWS,
    CKA_CHAR_SETS,
    CKA_COLOR,
    CKA_ENCODING_METHODS,
    CKA_HAS_RESET,
    CKA_HW_FEATURE_TYPE,
    CKA_MIME_TYPES,
    CKA_PIXEL_X,
    CKA_PIXEL_Y,
    CKA_RESET_ON_INIT,
    CKA_RESOLUTION,
    # CMS
    CKA_DEFAULT_CMS_ATTRIBUTES,
    CKA_REQUIRED_CMS_ATTRIBUTES,
    CKA_SUPPORTED_CMS_ATTRIBUTES,
    # NSS trust
    CKA_TRUST_CLIENT_AUTH,
    CKA_TRUST_CODE_SIGNING,
    CKA_TRUST_EMAIL_PROTECTION,
    CKA_TRUST_IPSEC_IKE,
    CKA_TRUST_OCSP_SIGNING,
    CKA_TRUST_SERVER_AUTH,
    CKA_TRUST_TIME_STAMPING,
    # X2 Ratchet (Double Ratchet)
    CKA_X2RATCHET_BAG,
    CKA_X2RATCHET_BAGSIZE,
    CKA_X2RATCHET_BOBS1STMSG,
    CKA_X2RATCHET_CKR,
    CKA_X2RATCHET_CKS,
    CKA_X2RATCHET_DHP,
    CKA_X2RATCHET_DHR,
    CKA_X2RATCHET_DHS,
    CKA_X2RATCHET_HKR,
    CKA_X2RATCHET_HKS,
    CKA_X2RATCHET_ISALICE,
    CKA_X2RATCHET_NHKR,
    CKA_X2RATCHET_NHKS,
    CKA_X2RATCHET_NR,
    CKA_X2RATCHET_NS,
    CKA_X2RATCHET_PNS,
    CKA_X2RATCHET_RK,
    CKA_VALUE,
    CKA_VALUE_BITS,
    CKA_VALUE_LEN,
    CKA_VERIFY,
    CKA_VERIFY_RECOVER,
    CKA_WRAP,
    CKA_WRAP_TEMPLATE,
    CKA_WRAP_WITH_TRUSTED,
)

# Attribute value types per OASIS PKCS#11 v3.2 spec.
#
# Types:
#   'bool'        — CK_BBOOL (1 byte)
#   'ulong'       — CK_ULONG or CK_ULONG-based enum (CK_OBJECT_CLASS, CK_KEY_TYPE, etc.)
#   'bytes'       — Byte array, big integer, opaque data
#   'str'         — RFC2279 UTF-8 string
#   'date'        — CK_DATE (8-byte YYYYMMDD)
#   'ulong_array' — Array of CK_ULONG (CK_MECHANISM_TYPE_PTR etc.)
#   'template'    — CK_ATTRIBUTE array (nested template)
#
# Attributes not in this table default to 'bytes' in read_attributes/attr_auto.
#
# Cross-checked against python-pkcs11/pkcs11/attributes.py in tests/test_raw_generation.py.

ATTR_VALUE_TYPES: dict[int, str] = {
    # --- Common object attributes ---
    int(CKA_CLASS): "ulong",
    int(CKA_TOKEN): "bool",
    int(CKA_PRIVATE): "bool",
    int(CKA_LABEL): "str",
    int(CKA_UNIQUE_ID): "str",
    int(CKA_APPLICATION): "str",
    int(CKA_VALUE): "bytes",
    int(CKA_OBJECT_ID): "bytes",
    int(CKA_CERTIFICATE_TYPE): "ulong",
    int(CKA_ISSUER): "bytes",
    int(CKA_SERIAL_NUMBER): "bytes",
    int(CKA_AC_ISSUER): "bytes",
    int(CKA_OWNER): "bytes",
    int(CKA_ATTR_TYPES): "bytes",
    int(CKA_TRUSTED): "bool",
    int(CKA_CERTIFICATE_CATEGORY): "ulong",
    int(CKA_JAVA_MIDP_SECURITY_DOMAIN): "ulong",
    int(CKA_URL): "str",
    int(CKA_HASH_OF_SUBJECT_PUBLIC_KEY): "bytes",
    int(CKA_HASH_OF_ISSUER_PUBLIC_KEY): "bytes",
    int(CKA_HASH_OF_CERTIFICATE): "bytes",
    int(CKA_NAME_HASH_ALGORITHM): "ulong",
    int(CKA_CHECK_VALUE): "bytes",
    int(CKA_PUBLIC_KEY_INFO): "bytes",
    int(CKA_SUBJECT): "bytes",
    int(CKA_ID): "bytes",
    # --- Key attributes ---
    int(CKA_KEY_TYPE): "ulong",
    int(CKA_SENSITIVE): "bool",
    int(CKA_ENCRYPT): "bool",
    int(CKA_DECRYPT): "bool",
    int(CKA_WRAP): "bool",
    int(CKA_UNWRAP): "bool",
    int(CKA_SIGN): "bool",
    int(CKA_SIGN_RECOVER): "bool",
    int(CKA_VERIFY): "bool",
    int(CKA_VERIFY_RECOVER): "bool",
    int(CKA_DERIVE): "bool",
    int(CKA_ENCAPSULATE): "bool",
    int(CKA_DECAPSULATE): "bool",
    int(CKA_START_DATE): "date",
    int(CKA_END_DATE): "date",
    int(CKA_MODULUS): "bytes",
    int(CKA_MODULUS_BITS): "ulong",
    int(CKA_PUBLIC_EXPONENT): "bytes",
    int(CKA_PRIVATE_EXPONENT): "bytes",
    int(CKA_PRIME_1): "bytes",
    int(CKA_PRIME_2): "bytes",
    int(CKA_EXPONENT_1): "bytes",
    int(CKA_EXPONENT_2): "bytes",
    int(CKA_COEFFICIENT): "bytes",
    int(CKA_PRIME): "bytes",
    int(CKA_SUBPRIME): "bytes",
    int(CKA_BASE): "bytes",
    int(CKA_PRIME_BITS): "ulong",
    int(CKA_SUBPRIME_BITS): "ulong",
    int(CKA_VALUE_BITS): "ulong",
    int(CKA_VALUE_LEN): "ulong",
    int(CKA_EXTRACTABLE): "bool",
    int(CKA_LOCAL): "bool",
    int(CKA_NEVER_EXTRACTABLE): "bool",
    int(CKA_ALWAYS_SENSITIVE): "bool",
    int(CKA_KEY_GEN_MECHANISM): "ulong",
    int(CKA_MODIFIABLE): "bool",
    int(CKA_COPYABLE): "bool",
    int(CKA_DESTROYABLE): "bool",
    int(CKA_EC_PARAMS): "bytes",
    int(CKA_EC_POINT): "bytes",
    int(CKA_ALWAYS_AUTHENTICATE): "bool",
    int(CKA_WRAP_WITH_TRUSTED): "bool",
    # --- Template attributes ---
    int(CKA_WRAP_TEMPLATE): "template",
    int(CKA_UNWRAP_TEMPLATE): "template",
    int(CKA_DERIVE_TEMPLATE): "template",
    int(CKA_ENCAPSULATE_TEMPLATE): "template",
    int(CKA_DECAPSULATE_TEMPLATE): "template",
    # --- Array attributes ---
    int(CKA_ALLOWED_MECHANISMS): "ulong_array",
    # --- Miscellaneous ---
    int(CKA_PROFILE_ID): "ulong",
    int(CKA_MECHANISM_TYPE): "ulong",
    int(CKA_PARAMETER_SET): "ulong",
    int(CKA_SEED): "bytes",
    int(CKA_PUBLIC_CRC64_VALUE): "bytes",
    # --- HSS attributes ---
    int(CKA_HSS_LEVELS): "ulong",
    int(CKA_HSS_LMS_TYPE): "ulong",
    int(CKA_HSS_LMOTS_TYPE): "ulong",
    int(CKA_HSS_LMS_TYPES): "ulong_array",
    int(CKA_HSS_LMOTS_TYPES): "ulong_array",
    int(CKA_HSS_KEYS_REMAINING): "ulong",
    # --- Validation attributes ---
    int(CKA_OBJECT_VALIDATION_FLAGS): "ulong",
    int(CKA_VALIDATION_TYPE): "ulong",
    int(CKA_VALIDATION_VERSION): "bytes",
    int(CKA_VALIDATION_LEVEL): "ulong",
    int(CKA_VALIDATION_MODULE_ID): "str",
    int(CKA_VALIDATION_FLAG): "ulong",
    int(CKA_VALIDATION_AUTHORITY_TYPE): "ulong",
    int(CKA_VALIDATION_COUNTRY): "str",
    int(CKA_VALIDATION_CERTIFICATE_IDENTIFIER): "str",
    int(CKA_VALIDATION_CERTIFICATE_URI): "str",
    int(CKA_VALIDATION_VENDOR_URI): "str",
    int(CKA_VALIDATION_PROFILE): "str",
    # --- GOST attributes ---
    int(CKA_GOSTR3410_PARAMS): "bytes",
    int(CKA_GOSTR3411_PARAMS): "bytes",
    int(CKA_GOST28147_PARAMS): "bytes",
    # --- Deprecated / legacy ---
    int(CKA_SECONDARY_AUTH): "bytes",  # deprecated in v2.11
    int(CKA_AUTH_PIN_FLAGS): "bytes",  # deprecated in v2.11
    # --- OTP attributes ---
    int(CKA_OTP_FORMAT): "ulong",
    int(CKA_OTP_LENGTH): "ulong",
    int(CKA_OTP_TIME_INTERVAL): "ulong",
    int(CKA_OTP_USER_FRIENDLY_MODE): "bool",
    int(CKA_OTP_CHALLENGE_REQUIREMENT): "ulong",
    int(CKA_OTP_TIME_REQUIREMENT): "ulong",
    int(CKA_OTP_COUNTER_REQUIREMENT): "ulong",
    int(CKA_OTP_PIN_REQUIREMENT): "ulong",
    int(CKA_OTP_USER_IDENTIFIER): "str",
    int(CKA_OTP_SERVICE_IDENTIFIER): "str",
    int(CKA_OTP_SERVICE_LOGO): "bytes",
    int(CKA_OTP_SERVICE_LOGO_TYPE): "str",
    int(CKA_OTP_COUNTER): "bytes",
    int(CKA_OTP_TIME): "str",
    # --- Hardware feature / display ---
    int(CKA_HW_FEATURE_TYPE): "ulong",
    int(CKA_RESET_ON_INIT): "bool",
    int(CKA_HAS_RESET): "bool",
    int(CKA_PIXEL_X): "ulong",
    int(CKA_PIXEL_Y): "ulong",
    int(CKA_RESOLUTION): "ulong",
    int(CKA_CHAR_ROWS): "ulong",
    int(CKA_CHAR_COLUMNS): "ulong",
    int(CKA_COLOR): "bool",
    int(CKA_BITS_PER_PIXEL): "ulong",
    int(CKA_CHAR_SETS): "str",
    int(CKA_ENCODING_METHODS): "str",
    int(CKA_MIME_TYPES): "str",
    # --- CMS ---
    int(CKA_REQUIRED_CMS_ATTRIBUTES): "bytes",
    int(CKA_DEFAULT_CMS_ATTRIBUTES): "bytes",
    int(CKA_SUPPORTED_CMS_ATTRIBUTES): "bytes",
    # --- NSS trust (vendor but widely used, CK_TRUST = CK_ULONG) ---
    int(CKA_TRUST_SERVER_AUTH): "ulong",
    int(CKA_TRUST_CLIENT_AUTH): "ulong",
    int(CKA_TRUST_CODE_SIGNING): "ulong",
    int(CKA_TRUST_EMAIL_PROTECTION): "ulong",
    int(CKA_TRUST_IPSEC_IKE): "ulong",
    int(CKA_TRUST_TIME_STAMPING): "ulong",
    int(CKA_TRUST_OCSP_SIGNING): "ulong",
    # --- X2 Ratchet (Double Ratchet) ---
    int(CKA_X2RATCHET_BAG): "bytes",
    int(CKA_X2RATCHET_BAGSIZE): "ulong",
    int(CKA_X2RATCHET_BOBS1STMSG): "bool",
    int(CKA_X2RATCHET_CKR): "bytes",
    int(CKA_X2RATCHET_CKS): "bytes",
    int(CKA_X2RATCHET_DHP): "bytes",
    int(CKA_X2RATCHET_DHR): "bytes",
    int(CKA_X2RATCHET_DHS): "bytes",
    int(CKA_X2RATCHET_HKR): "bytes",
    int(CKA_X2RATCHET_HKS): "bytes",
    int(CKA_X2RATCHET_ISALICE): "bool",
    int(CKA_X2RATCHET_NHKR): "bytes",
    int(CKA_X2RATCHET_NHKS): "bytes",
    int(CKA_X2RATCHET_NR): "ulong",
    int(CKA_X2RATCHET_NS): "ulong",
    int(CKA_X2RATCHET_PNS): "ulong",
    int(CKA_X2RATCHET_RK): "bytes",
    # --- Sentinel ---
    int(CKA_VENDOR_DEFINED): "bytes",  # vendor-defined attrs default to bytes
}
