"""Curated attribute value type metadata per OASIS PKCS#11 v3.2 spec.

This is NOT generated from C headers (headers don't contain type info).
It is manually maintained from the OASIS spec attribute tables and
cross-checked against python-pkcs11/pkcs11/attributes.py in tests.

Edit this file directly when adding new attributes or fixing types.
"""

from __future__ import annotations

from .types_std import (
    # Common object attributes
    CKA_AC_ISSUER,
    CKA_ALLOWED_MECHANISMS,
    CKA_ALWAYS_AUTHENTICATE,
    CKA_ALWAYS_SENSITIVE,
    CKA_APPLICATION,
    CKA_ATTR_TYPES,
    # Deprecated / legacy
    CKA_AUTH_PIN_FLAGS,
    CKA_BASE,
    # Hardware feature / display
    CKA_BITS_PER_PIXEL,
    CKA_CERTIFICATE_CATEGORY,
    CKA_CERTIFICATE_TYPE,
    CKA_CHAR_COLUMNS,
    CKA_CHAR_ROWS,
    CKA_CHAR_SETS,
    CKA_CHECK_VALUE,
    CKA_CLASS,
    CKA_COEFFICIENT,
    CKA_COLOR,
    CKA_COPYABLE,
    CKA_DECAPSULATE,
    CKA_DECAPSULATE_TEMPLATE,
    CKA_DECRYPT,
    # CMS
    CKA_DEFAULT_CMS_ATTRIBUTES,
    CKA_DERIVE,
    CKA_DERIVE_TEMPLATE,
    CKA_DESTROYABLE,
    CKA_EC_PARAMS,
    CKA_EC_POINT,
    CKA_ENCAPSULATE,
    CKA_ENCAPSULATE_TEMPLATE,
    CKA_ENCODING_METHODS,
    CKA_ENCRYPT,
    CKA_END_DATE,
    CKA_EXPONENT_1,
    CKA_EXPONENT_2,
    CKA_EXTRACTABLE,
    # GOST
    CKA_GOST28147_PARAMS,
    CKA_GOSTR3410_PARAMS,
    CKA_GOSTR3411_PARAMS,
    CKA_HAS_RESET,
    CKA_HASH_OF_CERTIFICATE,
    CKA_HASH_OF_ISSUER_PUBLIC_KEY,
    CKA_HASH_OF_SUBJECT_PUBLIC_KEY,
    CKA_HSS_KEYS_REMAINING,
    CKA_HSS_LEVELS,
    CKA_HSS_LMOTS_TYPE,
    CKA_HSS_LMOTS_TYPES,
    CKA_HSS_LMS_TYPE,
    CKA_HSS_LMS_TYPES,
    CKA_HW_FEATURE_TYPE,
    CKA_ID,
    CKA_ISSUER,
    CKA_JAVA_MIDP_SECURITY_DOMAIN,
    CKA_KEY_GEN_MECHANISM,
    CKA_KEY_TYPE,
    CKA_LABEL,
    CKA_LOCAL,
    CKA_MECHANISM_TYPE,
    CKA_MIME_TYPES,
    CKA_MODIFIABLE,
    CKA_MODULUS,
    CKA_MODULUS_BITS,
    CKA_NAME_HASH_ALGORITHM,
    CKA_NEVER_EXTRACTABLE,
    CKA_OBJECT_ID,
    CKA_OBJECT_VALIDATION_FLAGS,
    # OTP attributes
    CKA_OTP_CHALLENGE_REQUIREMENT,
    CKA_OTP_COUNTER,
    CKA_OTP_COUNTER_REQUIREMENT,
    CKA_OTP_FORMAT,
    CKA_OTP_LENGTH,
    CKA_OTP_PIN_REQUIREMENT,
    CKA_OTP_SERVICE_IDENTIFIER,
    CKA_OTP_SERVICE_LOGO,
    CKA_OTP_SERVICE_LOGO_TYPE,
    CKA_OTP_TIME,
    CKA_OTP_TIME_INTERVAL,
    CKA_OTP_TIME_REQUIREMENT,
    CKA_OTP_USER_FRIENDLY_MODE,
    CKA_OTP_USER_IDENTIFIER,
    CKA_OWNER,
    CKA_PARAMETER_SET,
    CKA_PIXEL_X,
    CKA_PIXEL_Y,
    CKA_PRIME,
    CKA_PRIME_1,
    CKA_PRIME_2,
    CKA_PRIME_BITS,
    CKA_PRIVATE,
    CKA_PRIVATE_EXPONENT,
    CKA_PROFILE_ID,
    CKA_PUBLIC_CRC64_VALUE,
    CKA_PUBLIC_EXPONENT,
    CKA_PUBLIC_KEY_INFO,
    CKA_REQUIRED_CMS_ATTRIBUTES,
    CKA_RESET_ON_INIT,
    CKA_RESOLUTION,
    CKA_SECONDARY_AUTH,
    CKA_SEED,
    CKA_SENSITIVE,
    CKA_SERIAL_NUMBER,
    CKA_SIGN,
    CKA_SIGN_RECOVER,
    CKA_START_DATE,
    CKA_SUBJECT,
    CKA_SUBPRIME,
    CKA_SUBPRIME_BITS,
    CKA_SUPPORTED_CMS_ATTRIBUTES,
    CKA_TOKEN,
    # NSS trust
    CKA_TRUST_CLIENT_AUTH,
    CKA_TRUST_CODE_SIGNING,
    CKA_TRUST_EMAIL_PROTECTION,
    CKA_TRUST_IPSEC_IKE,
    CKA_TRUST_OCSP_SIGNING,
    CKA_TRUST_SERVER_AUTH,
    CKA_TRUST_TIME_STAMPING,
    CKA_TRUSTED,
    CKA_UNIQUE_ID,
    CKA_UNWRAP,
    CKA_UNWRAP_TEMPLATE,
    CKA_URL,
    CKA_VALIDATION_AUTHORITY_TYPE,
    CKA_VALIDATION_CERTIFICATE_IDENTIFIER,
    CKA_VALIDATION_CERTIFICATE_URI,
    CKA_VALIDATION_COUNTRY,
    CKA_VALIDATION_FLAG,
    CKA_VALIDATION_LEVEL,
    CKA_VALIDATION_MODULE_ID,
    CKA_VALIDATION_PROFILE,
    CKA_VALIDATION_TYPE,
    CKA_VALIDATION_VENDOR_URI,
    CKA_VALIDATION_VERSION,
    CKA_VALUE,
    CKA_VALUE_BITS,
    CKA_VALUE_LEN,
    CKA_VENDOR_DEFINED,
    CKA_VERIFY,
    CKA_VERIFY_RECOVER,
    CKA_WRAP,
    CKA_WRAP_TEMPLATE,
    CKA_WRAP_WITH_TRUSTED,
    # X2 Ratchet (Double Ratchet)
    CKA_X2RATCHET_BAG,
    CKA_X2RATCHET_BAGSIZE,
    CKA_X2RATCHET_BOBS1STMSG,
    CKA_X2RATCHET_CKR,
    CKA_X2RATCHET_CKS,
    CKA_X2RATCHET_DHP,
    CKA_X2RATCHET_DHR,
    CKA_X2RATCHET_DHS,
    CKA_X2RATCHET_HKR,
    CKA_X2RATCHET_HKS,
    CKA_X2RATCHET_ISALICE,
    CKA_X2RATCHET_NHKR,
    CKA_X2RATCHET_NHKS,
    CKA_X2RATCHET_NR,
    CKA_X2RATCHET_NS,
    CKA_X2RATCHET_PNS,
    CKA_X2RATCHET_RK,
)

# Attribute value types per OASIS PKCS#11 v3.2 spec.
#
# Types:
#   'bool'        — CK_BBOOL (1 byte)
#   'ulong'       — CK_ULONG or CK_ULONG-based enum (CK_OBJECT_CLASS, CK_KEY_TYPE, etc.)
#   'bytes'       — Byte array, big integer, opaque data
#   'str'         — RFC2279 UTF-8 string
#   'date'        — CK_DATE (8-byte YYYYMMDD)
#   'ulong_array' — Array of CK_ULONG (CK_MECHANISM_TYPE_PTR etc.)
#   'template'    — CK_ATTRIBUTE array (nested template)
#
# Attributes not in this table default to 'bytes' in read_attributes/attr_auto.
#
# Cross-checked against python-pkcs11/pkcs11/attributes.py in tests/test_raw_generation.py.

ATTR_VALUE_TYPES: dict[int, str] = {
    # --- Common object attributes ---
    CKA_CLASS: "ulong",
    CKA_TOKEN: "bool",
    CKA_PRIVATE: "bool",
    CKA_LABEL: "str",
    CKA_UNIQUE_ID: "str",
    CKA_APPLICATION: "str",
    CKA_VALUE: "bytes",
    CKA_OBJECT_ID: "bytes",
    CKA_CERTIFICATE_TYPE: "ulong",
    CKA_ISSUER: "bytes",
    CKA_SERIAL_NUMBER: "bytes",
    CKA_AC_ISSUER: "bytes",
    CKA_OWNER: "bytes",
    CKA_ATTR_TYPES: "bytes",
    CKA_TRUSTED: "bool",
    CKA_CERTIFICATE_CATEGORY: "ulong",
    CKA_JAVA_MIDP_SECURITY_DOMAIN: "ulong",
    CKA_URL: "str",
    CKA_HASH_OF_SUBJECT_PUBLIC_KEY: "bytes",
    CKA_HASH_OF_ISSUER_PUBLIC_KEY: "bytes",
    CKA_HASH_OF_CERTIFICATE: "bytes",
    CKA_NAME_HASH_ALGORITHM: "ulong",
    CKA_CHECK_VALUE: "bytes",
    CKA_PUBLIC_KEY_INFO: "bytes",
    CKA_SUBJECT: "bytes",
    CKA_ID: "bytes",
    # --- Key attributes ---
    CKA_KEY_TYPE: "ulong",
    CKA_SENSITIVE: "bool",
    CKA_ENCRYPT: "bool",
    CKA_DECRYPT: "bool",
    CKA_WRAP: "bool",
    CKA_UNWRAP: "bool",
    CKA_SIGN: "bool",
    CKA_SIGN_RECOVER: "bool",
    CKA_VERIFY: "bool",
    CKA_VERIFY_RECOVER: "bool",
    CKA_DERIVE: "bool",
    CKA_ENCAPSULATE: "bool",
    CKA_DECAPSULATE: "bool",
    CKA_START_DATE: "date",
    CKA_END_DATE: "date",
    CKA_MODULUS: "bytes",
    CKA_MODULUS_BITS: "ulong",
    CKA_PUBLIC_EXPONENT: "bytes",
    CKA_PRIVATE_EXPONENT: "bytes",
    CKA_PRIME_1: "bytes",
    CKA_PRIME_2: "bytes",
    CKA_EXPONENT_1: "bytes",
    CKA_EXPONENT_2: "bytes",
    CKA_COEFFICIENT: "bytes",
    CKA_PRIME: "bytes",
    CKA_SUBPRIME: "bytes",
    CKA_BASE: "bytes",
    CKA_PRIME_BITS: "ulong",
    CKA_SUBPRIME_BITS: "ulong",
    CKA_VALUE_BITS: "ulong",
    CKA_VALUE_LEN: "ulong",
    CKA_EXTRACTABLE: "bool",
    CKA_LOCAL: "bool",
    CKA_NEVER_EXTRACTABLE: "bool",
    CKA_ALWAYS_SENSITIVE: "bool",
    CKA_KEY_GEN_MECHANISM: "ulong",
    CKA_MODIFIABLE: "bool",
    CKA_COPYABLE: "bool",
    CKA_DESTROYABLE: "bool",
    CKA_EC_PARAMS: "bytes",
    CKA_EC_POINT: "bytes",
    CKA_ALWAYS_AUTHENTICATE: "bool",
    CKA_WRAP_WITH_TRUSTED: "bool",
    # --- Template attributes ---
    CKA_WRAP_TEMPLATE: "template",
    CKA_UNWRAP_TEMPLATE: "template",
    CKA_DERIVE_TEMPLATE: "template",
    CKA_ENCAPSULATE_TEMPLATE: "template",
    CKA_DECAPSULATE_TEMPLATE: "template",
    # --- Array attributes ---
    CKA_ALLOWED_MECHANISMS: "ulong_array",
    # --- Miscellaneous ---
    CKA_PROFILE_ID: "ulong",
    CKA_MECHANISM_TYPE: "ulong",
    CKA_PARAMETER_SET: "ulong",
    CKA_SEED: "bytes",
    CKA_PUBLIC_CRC64_VALUE: "bytes",
    # --- HSS attributes ---
    CKA_HSS_LEVELS: "ulong",
    CKA_HSS_LMS_TYPE: "ulong",
    CKA_HSS_LMOTS_TYPE: "ulong",
    CKA_HSS_LMS_TYPES: "ulong_array",
    CKA_HSS_LMOTS_TYPES: "ulong_array",
    CKA_HSS_KEYS_REMAINING: "ulong",
    # --- Validation attributes ---
    CKA_OBJECT_VALIDATION_FLAGS: "ulong",
    CKA_VALIDATION_TYPE: "ulong",
    CKA_VALIDATION_VERSION: "bytes",
    CKA_VALIDATION_LEVEL: "ulong",
    CKA_VALIDATION_MODULE_ID: "str",
    CKA_VALIDATION_FLAG: "ulong",
    CKA_VALIDATION_AUTHORITY_TYPE: "ulong",
    CKA_VALIDATION_COUNTRY: "str",
    CKA_VALIDATION_CERTIFICATE_IDENTIFIER: "str",
    CKA_VALIDATION_CERTIFICATE_URI: "str",
    CKA_VALIDATION_VENDOR_URI: "str",
    CKA_VALIDATION_PROFILE: "str",
    # --- GOST attributes ---
    CKA_GOSTR3410_PARAMS: "bytes",
    CKA_GOSTR3411_PARAMS: "bytes",
    CKA_GOST28147_PARAMS: "bytes",
    # --- Deprecated / legacy ---
    CKA_SECONDARY_AUTH: "bytes",  # deprecated in v2.11
    CKA_AUTH_PIN_FLAGS: "bytes",  # deprecated in v2.11
    # --- OTP attributes ---
    CKA_OTP_FORMAT: "ulong",
    CKA_OTP_LENGTH: "ulong",
    CKA_OTP_TIME_INTERVAL: "ulong",
    CKA_OTP_USER_FRIENDLY_MODE: "bool",
    CKA_OTP_CHALLENGE_REQUIREMENT: "ulong",
    CKA_OTP_TIME_REQUIREMENT: "ulong",
    CKA_OTP_COUNTER_REQUIREMENT: "ulong",
    CKA_OTP_PIN_REQUIREMENT: "ulong",
    CKA_OTP_USER_IDENTIFIER: "str",
    CKA_OTP_SERVICE_IDENTIFIER: "str",
    CKA_OTP_SERVICE_LOGO: "bytes",
    CKA_OTP_SERVICE_LOGO_TYPE: "str",
    CKA_OTP_COUNTER: "bytes",
    CKA_OTP_TIME: "str",
    # --- Hardware feature / display ---
    CKA_HW_FEATURE_TYPE: "ulong",
    CKA_RESET_ON_INIT: "bool",
    CKA_HAS_RESET: "bool",
    CKA_PIXEL_X: "ulong",
    CKA_PIXEL_Y: "ulong",
    CKA_RESOLUTION: "ulong",
    CKA_CHAR_ROWS: "ulong",
    CKA_CHAR_COLUMNS: "ulong",
    CKA_COLOR: "bool",
    CKA_BITS_PER_PIXEL: "ulong",
    CKA_CHAR_SETS: "str",
    CKA_ENCODING_METHODS: "str",
    CKA_MIME_TYPES: "str",
    # --- CMS ---
    CKA_REQUIRED_CMS_ATTRIBUTES: "bytes",
    CKA_DEFAULT_CMS_ATTRIBUTES: "bytes",
    CKA_SUPPORTED_CMS_ATTRIBUTES: "bytes",
    # --- NSS trust (vendor but widely used, CK_TRUST = CK_ULONG) ---
    CKA_TRUST_SERVER_AUTH: "ulong",
    CKA_TRUST_CLIENT_AUTH: "ulong",
    CKA_TRUST_CODE_SIGNING: "ulong",
    CKA_TRUST_EMAIL_PROTECTION: "ulong",
    CKA_TRUST_IPSEC_IKE: "ulong",
    CKA_TRUST_TIME_STAMPING: "ulong",
    CKA_TRUST_OCSP_SIGNING: "ulong",
    # --- X2 Ratchet (Double Ratchet) ---
    CKA_X2RATCHET_BAG: "bytes",
    CKA_X2RATCHET_BAGSIZE: "ulong",
    CKA_X2RATCHET_BOBS1STMSG: "bool",
    CKA_X2RATCHET_CKR: "bytes",
    CKA_X2RATCHET_CKS: "bytes",
    CKA_X2RATCHET_DHP: "bytes",
    CKA_X2RATCHET_DHR: "bytes",
    CKA_X2RATCHET_DHS: "bytes",
    CKA_X2RATCHET_HKR: "bytes",
    CKA_X2RATCHET_HKS: "bytes",
    CKA_X2RATCHET_ISALICE: "bool",
    CKA_X2RATCHET_NHKR: "bytes",
    CKA_X2RATCHET_NHKS: "bytes",
    CKA_X2RATCHET_NR: "ulong",
    CKA_X2RATCHET_NS: "ulong",
    CKA_X2RATCHET_PNS: "ulong",
    CKA_X2RATCHET_RK: "bytes",
    # --- Sentinel ---
    CKA_VENDOR_DEFINED: "bytes",  # vendor-defined attrs default to bytes
}
